### ISSUE TITLE
overrideValue in field.render()'s custom options no longer working as of 3.12

### ISSUE THREAD

**Issue by beneberle** [solspace/craft-freeform#250]
**Describe the bug or issue you're experiencing**

After updating Freeform from 3.11 to 3.12.7, my template's field.render() calls  are no longer loading with an `overrideValue` as specified.

The docs I'm referring to: https://docs.solspace.com/craft/freeform/v3/template-objects/field.html#usage-in-templates

**Steps to reproduce**

1. Install demo templates.
2. Update templates/freeform-demo/bootstrap/_form.html, line 257-264, adding an overrideValue:
```
{{ field.render({ 
	class: class,  
	labelClass: labelClass,  
	instructionsClass: instructionClass,  
	instructionsBelowField: true,  
	errorClass: errorClass,  
	overrideValue: "TEST"  
    })  
}} 
```
**Expected behavior**

Standard text fields in my form pre-populate with "TEST"
 
**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.23
- Freeform Version: 3.12.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: No

**Additional context**

I can get the pre-population to work by passing an overrideValues object as second param when loading the form using craft.freeform.form(), but not for individual fields when looping thru the form fields for custom rendering.

**Comment by kjmartens** [comment]
Thanks for reporting this @beneberle. I can duplicate this as well. We'll get a fix for it shortly. 🙂

**Comment by kjmartens** [comment]
This is an issue that is complex to resolve, and likely cannot address, unfortunately. In the meantime, we suggest anyone affected by this to override values at the form level instead:

```
{{ craft.freeform.form("myForm", {
  labelClass: "form-label",
  inputClass: "form-control",
  overrideValues: {
    firstName: currentUser.name,
    myHiddenFieldHandle: entry.id,
    anotherField: "something else",
  }
}).render() }}
```
