### ISSUE TITLE
`m220223_123305_AddQuickExportPermissions` clobbers Project Config changes due to group permissions assignment

### ISSUE THREAD

**Issue by AugustMiller** [solspace/craft-freeform#304]
**Describe the bug or issue you're experiencing**

When I run the latest migration—say, via `craft up`, FreeForm [modifies the current Project Config state](https://github.com/solspace/craft3-freeform/blob/master/packages/plugin/src/migrations/m220223_123305_AddQuickExportPermissions.php#L60-L71) by adding permissions, which in turn writes out the stored state, overwriting any pending local changes with those stored in the Project Config table.

As a result, when the subsequent `project-config/apply` action is run, the on-disk data no longer represents the desired schema, and nothing is updated.

Additionally, this also updates the `dateModified`, which means that trying to manually "reject" the changes in git results in an older on-disk state than DB state, Craft will not acknowledge the “real” local PC changes, without a new `craft project-config/touch`.

In general, Migrations should not modify Project Config, and Project Config should not trigger migrations—they're designed to be run serially (and atomically).

**Steps to reproduce**

1. Make some local Project Config changes;
2. Update to FreeForm to 3.13.6 (or ^3.13.4);
3. Clone the project and `craft up` in a new environment;
4. Observe reverted changes to `config/project` YAML files and absence of desired changes in Craft;
5. …

**Exected behavior**

New migrations and project config updates are applied in sequence.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.37
- Freeform Version: 3.13.6
- Freeform Edition: Pro
- Fresh Install or Upgrade: Update

**Comment by AugustMiller** [comment]
It looks like other migrations may be affected by this same bug…

- https://github.com/solspace/craft3-freeform/blob/master/packages/plugin/src/migrations/m210413_104951_MigrateSubmissionPermissions.php
- https://github.com/solspace/craft3-freeform/blob/master/packages/plugin/src/migrations/m210416_072726_MigrateFormPermissions.php

**Comment by AugustMiller** [comment]
Ok, after further investigation, this is mostly a problem when working with others and applying migrations in a development environment when `allowAdminChanges` is `true` (and therefore `ProjectConfig::readOnly` is not).

So, if I flip our app over to `ENV=production`, or just bang it out to the live server, FreeForm is not symptomatic. However, when integrating changes from another developer without having gone out to production or them having shared a database backup, this is still very much an issue.

**Comment by khalwat** [comment]
I just ran into this too in local dev after updating FreeForm... it wiped out any permissions after it. Thankfully I knew about it, so I restored the chunk from the `.yaml` before pushing to production

**Comment by kjmartens** [comment]
Thanks, and sorry for the trouble. We'll work on a fix shortly.
