### ISSUE TITLE
Drag and Drop File Upload field says “too many files uploaded"

### ISSUE THREAD

**Issue by TUSAB-web** [solspace/craft-freeform#305]
**Describe the bug or issue you're experiencing**

Sometimes when people drag files to the drag-and-drop files field, the system returns an error of “too many files uploaded” even if it’s just one file.

**Steps to reproduce**

1. Create a drag-and-drop file field
2. User drags a file to the field
3. Above error (sometimes)

**Expected behavior**

The file shows up without an error.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.36
- Freeform Version: 3.13.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

Site uses Blitz caching, but we have been using CSRF token generation without any issues on forms.

**Comment by kjmartens** [comment]
Hi @TUSAB-web,

Sorry for the delay and the issue you're experiencing. I am trying to duplicate this on my end and cannot at the moment. Are you able to provide a bit more info? 🙂 

1. Where is the error displaying? Does it happen while uploading files, or upon submit of the form? Perhaps a screenshot would help?
2. In your own testing, how often does it appear to happen? Once every 10 times, once every 100 times, etc?
3. Which browser (and version) are you testing in?
4. What is your configuration for the File field set to? For example, which field types do you allow, what is the maximum number of files, maximum size of files, etc?
5. Which file types are you attempting to upload? And what is your process like? E.g. Do you drag over 1 file, then another, then another and get the error? Or does it happen when doing different interactions? 🙂

**Comment by TUSAB-web** [comment]
1. It appears while uploading
2. Not sure, but probably 1 of 10.
3. Safari and Chrome
4. The max size is 15MB, File Count is 1.
5. The only allowed file type is PDF.

I am doing more testing and will get back to you with those results.

**Comment by kjmartens** [comment]
Hi @TUSAB-web,

Just following up to see if you were able to figure this one out, or if you still needed assistance with it. 🙂

**Comment by PiessensLander** [comment]
Hi @kjmartens - I just stumbled upon this issue whilst researching the same behaviour on my site. I wonder if there has been any update around this issue? Please find the steps to reproduce and an example below:

- Enable AJAX on the form
- Add a file drag & drop to the form
- Allow only 1 file to be uploaded
- Allow only images and PDF files with a 2048KB file size limit
- On the frontend, fill in the form and upload a file
- Do not submit the form and refresh the page
- Upload the file again
- Freeform shows error


Craft & Plugin Info (please complete the following information):

Craft Version: 4.10.4
Freeform Version: 5.3.4
Freeform Edition: Pro
Fresh Install or Upgrade: Upgrade


https://github.com/solspace/craft-freeform/assets/55790048/1861568d-1b54-439f-aa63-10868f8eb180
