### ISSUE TITLE
Accessing Diagnostic page throws error

### ISSUE THREAD

**Issue by rostockahoi** [solspace/craft-freeform#307]
**Describe the bug or issue you're experiencing**

Accessing diagnostic page throws error: `array_values() expects parameter 1 to be array, null given` in `/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Events/Forms/Types/RegisterFormTypeEvent.php:37`

**Steps to reproduce**

1. Access diagnostic page at /admin/freeform/settings/diagnostics

**Expected behavior**

Show diagnostic page

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.37
- Freeform Version: 3.13.6
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

Changing line 37 in `packages/plugin/src/Events/Forms/Types/RegisterFormTypeEvent.php` from `return array_values($this->types);` to `return is_array($this->types) ? array_values($this->types) : [];` makes the page work. I don't know what's missing there though, maybe one of the stats numbers there.

**Comment by kjmartens** [comment]
Hi @rostockahoi. Sorry for the trouble. This is now fixed in Freeform 3.13.7. It's a check that is specific to the new Form Types feature in Freeform. 🙂
