### ISSUE TITLE
Drag and drop field XMLHttpRequest gives a 404 in local development

### ISSUE THREAD

**Issue by FrDH** [solspace/craft-freeform#319]
**Describe the bug or issue you're experiencing**
When I try to upload files to the "File Drag and drop" field, the console gives me a 404 error (and ofcourse the file isn't uploaded).
After inspecting the request, I found the request URL is: `http://localhost/freeform/files/upload`, where (I think) it should have been `http://localhost/my-website/public_html/freeform/files/upload`.

I guess this issue will go away when on a live environment, but could it not be fixed anyway so it works on local environments as well?

**Steps to reproduce**

1. Create a form
2. Add a "File drag and drop" field
3. Visit the form on the frontend and upload a file (local development).

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.37
- Freeform Version: 3.13.7
- Freeform Edition:pro
- Fresh Install or Upgrade: new install

**Additional context**
Not sure if it's relevant, but I'm using a multi-page form, the drag and drop field is on the second (of three) page.
![Schermafbeelding 2022-04-11 om 14 34 18](https://user-images.githubusercontent.com/1387163/162740251-4be60a46-9463-4fbc-94e9-2693d54d0328.png)

**Comment by kjmartens** [comment]
Sorry for the trouble @FrDH. You're right that you likely won't experience any issues with this in your live environment. However, I've made a note about this issue and we'll see if we can adjust it to account for irregular URLs like this. 🙂

**Comment by kjmartens** [comment]
Hi @FrDH, this should be resolved in Freeform 3.13.8 now. 🙂
