### ISSUE TITLE
[4.0.0-beta.2] composer error league/flysystem

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft-freeform#321]
**Describe the bug or issue you're experiencing**
When installing freeform 4.0.0-beta.2 in combination with craftcms/aws-s3 2.0.0-beta.3, composer is throwing an error on the league/flysystem https://i.imgur.com/jZriiJU.png.
I guess you should probably also use this https://github.com/craftcms/flysystem implementation

**Steps to reproduce**

1. install craftcms/aws-s3 2.0.0-beta.3 and solspace/craft-freeform 4.0.0-beta.2

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.0-beta.4
- Freeform Version: 4.0.0-beta.2
- Fresh Install or Upgrade: Fresh install

**Comment by kjmartens** [comment]
Sorry for the trouble, @WHITE-developer.

I've just updated the dependency versions to include both 2.0 and 3.0. Can you try updating to `dev-v4.0/master` and see if it works for you?

I've made a note about the Craft implementation and we'll check into that shortly. 🙂

**Comment by WHITE-developer** [comment]
@kjmartens just managed to install freeform,
Thanks for the quick fix! :+1:
