### ISSUE TITLE
Default template isn't applying to new forms

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#324]
**Describe the bug or issue you're experiencing**

The default formatting template doesn't seem to be getting applied on the live server. I've set it locally, and it seems to work locally:

![image](https://user-images.githubusercontent.com/1250017/165450350-59065478-4868-4a16-b199-cb3d191d50f9.png)

I've committed that to project confirm and deployed it, and verified that's what it's meant to be using on the live server

![image](https://user-images.githubusercontent.com/1250017/165450263-7abdfc28-dd8c-4f07-b8c3-335f5dfe84b2.png)

But then when I click New on the Freeform Dashboard, it's set to something else:

![image](https://user-images.githubusercontent.com/1250017/165450286-e7fbdd3c-87b5-42bf-91a3-22a5453d73c5.png)

I've also re-applied all project config changes through Utilities. Any ideas?

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.38
- Freeform Version: 3.13.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @darylknight,

I can't seem to duplicate this on my end. Have you cleared Craft's cache and browser cache as well? 🙂

**Comment by darylknight** [comment]
Yeah I thought that might be the case. I'm just struggling to pin it down.

- Cleared the browser cache
- Used private browsing mode
- Switched to another site (although Freeform doesn't support multi-site anyway)
- Changed the default formatting template to something else, deployed, applied migrations, cleared caches, tried again (it still shows Flexbox)
- Changed it back to Bootstrap 5. It still defaults to Flexbox
I guess the weird thing is that it works locally, but not on the live site., Even though it is applying project config changes, clearing caches and applying settings. And the project config is clearly correct, it's just not working.

I guess we can close this out as it appears to be related to environment - I just have no idea why!

**Comment by kjmartens** [comment]
Hmm, yeah it is weird. I do feel like I've temporarily experienced this one time myself, but then it went away. I'll make a note about it and we'll keep our eye on it. If anything else comes up for you, let me know. 🙂

**Comment by corneliusio** [comment]
@kjmartens Wondering if we could re-open this issue. My team is experiencing this on a client site currently. "Default Formatting Template" is set to "Grid" but this is not being respected when a new form is created. I **am** seeing a difference between environments, however, neither of the values being used for new forms match what is set for "Default Formatting Template".

Craft Version: 3.7.39
Freeform Version: 3.13.7
Freeform Edition: Pro
Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
@corneliusio and @darylknight, are you able to copy and paste the server response you're getting on the Dashboard or Forms CP pages? Look for `options` in the Network tab...

<img width="853" alt="Screen Shot 2022-05-03 at 11 38 19 AM" src="https://user-images.githubusercontent.com/1821674/166499836-4383e662-0a1a-4489-81f1-a751a36bcf3e.png">

**Comment by kjmartens** [comment]
Thanks for this @corneliusio. After playing around with it a little longer, I was able to reproduce this issue when I don't have any custom formatting templates. The error seems to stem from that. We'll work on a fix shortly. 🙂

**Comment by darylknight** [comment]
Same here - the options object is correct:

```{"types":[{"className":"Solspace\\Freeform\\Form\\Types\\Regular","name":"Regular","properties":[]}],"statuses":[{"name":"Pending","id":1,"isDefault":false},{"name":"Open","id":2,"isDefault":true},{"name":"Closed","id":3,"isDefault":false}],"templates":{"native":[{"id":"flexbox.html","name":"Flexbox"},{"id":"foundation.html","name":"Foundation"},{"id":"bootstrap.html","name":"Bootstrap"},{"id":"bootstrap-5.html","name":"Bootstrap 5"},{"id":"bootstrap-4.html","name":"Bootstrap 4"},{"id":"tailwind.html","name":"Tailwind"},{"id":"grid.html","name":"Grid"}],"custom":[],"success":[],"default":"bootstrap-5.html"},"ajax":true}```

However, it still shows Flexbox in the dropdown.

**Comment by kjmartens** [comment]
This should be fixed in Freeform 3.13.9 now 🙂

**Comment by darylknight** [comment]
Excellent, thank you!

**Comment by corneliusio** [comment]
@gustavs-gutmanis @kjmartens Just tested with `dev-master` and everything's working as expected now. Thanks!
