### ISSUE TITLE
PHP Notice – yii\base\ErrorException - Undefined offset: 0 when load form with craft cache

### ISSUE THREAD

**Issue by amici-infotech** [solspace/craft-freeform#325]
I am getting this weired error screen where craft cms fails to register preregistered CSS files and throw error on this line.

![image](https://user-images.githubusercontent.com/20450552/165487491-9fbebbdc-850f-4e1f-9879-82d3394dfe01.png)

If I remove this bit from freeform form template, it works.
![image](https://user-images.githubusercontent.com/20450552/165489365-cb6ec474-f28b-433a-9cff-51d61846b16c.png)

**Steps to reproduce**

1. Install craft freeform
2. Add cache tag in template and load freeform form

**Craft & Plugin Info:**

- Craft Version: 3.7.39 (PRO)
- Freeform Version: 3.13.7
- Freeform Edition: PRO
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
Hi @amici-infotech,

Sorry for the trouble you're experiencing. Can you clarify where you're placing the cache tag? Is it inside the Freeform formatting template, the regular template that loads the form, or some other layout template? And is so, what does the full template look like (feel free to minimize the template to just include key parts but still fail)? 🙂

**Comment by amici-infotech** [comment]
Cache tag is in layouts file. so I can cache whole site just once.. here is how my html will look like
```
{% cache globally using key 'pages/' ~ craft.app.request.pathInfo ~ '/' ~ craft.app.request.queryStringWithoutPath %}
<!DOCTYPE html>
{% set htmlAttributes = {
	lang: "en",
	class: [
		'overflow-x-hidden',
	]
} %}
<html {{ attr(htmlAttributes) }}>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
</head>

<body>
	{{ craft.freeform.form(block.form.handle, {
	    labelClass: "",
	    inputClass: "",
	    instructionsBelowField: true,
	    overrideValues: {
	        pageId: entry.id ?? '',
	        pageUrl: entry.url ?? '',
	    }
	}).render() }}
</body>
</html>
{% endcache %}
```

**Comment by kjmartens** [comment]
Thanks for the additional info, @amici-infotech. I did some digging around and, assuming you have a custom formatting template, I believe this is a documentation error you may have copied. The `{% css formCss %}` tag is only meant for default formatting templates and won't do anything for custom ones. It is odd that cache chokes on it, but that is a moot point I suppose. I see that our documentation does include this in examples, so I apologize for that.

When you remove that `{% css formCss %}` tag, I assume there is no negative impact to your form display? If there is, please let me know.

In the meantime, we'll update our documentation and also see if we can improve this further so even the default formatting templates don't need them, thus cleaning things up a bit and removing further confusion. 🙂
