### ISSUE TITLE
[4.0.0-beta] Can't install via composer without -W / --with-all-dependencies flag

### ISSUE THREAD

**Issue by tomdavies** [solspace/craft-freeform#326]
With the most minimal possible Craft 4-RC1 `composer.json` (see end of issue) it is not possible to install the Freeform beta without passing `-W` to allow up/downgrades of locked packages. 

**Steps to reproduce**

1. Create project with `composer.json` as provided
2. `composer require solspace/craft-freeform:4.0.0-beta.3`
3. Error occurs:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpoffice/phpspreadsheet[1.6.0, ..., 1.8.2] require php ^5.6|^7.0 -> your php version (8.0.17; overridden via config.platform, same as actual) does not satisfy that requirement.
    - phpoffice/phpspreadsheet[1.9.0, ..., 1.12.0] require php ^7.1 -> your php version (8.0.17; overridden via config.platform, same as actual) does not satisfy that requirement.
    - phpoffice/phpspreadsheet[1.13.0, ..., 1.14.1] require php ^7.2 -> your php version (8.0.17; overridden via config.platform, same as actual) does not satisfy that requirement.
    - phpoffice/phpspreadsheet[1.15.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpoffice/phpspreadsheet 1.23.0 requires psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - solspace/craft-freeform 4.0.0-beta.3 requires phpoffice/phpspreadsheet ^1.6.0 -> satisfiable by phpoffice/phpspreadsheet[1.6.0, ..., 1.23.0].
    - Root composer.json requires solspace/craft-freeform 4.0.0-beta.3 -> satisfiable by solspace/craft-freeform[4.0.0-beta.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Running `composer require solspace/craft-freeform:4.0.0-beta.3 -W` works, but surely shouldn't be expected to be required?

**Expected behavior**

I can install the beta without setting `-W` / `--with-all-dependencies `

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.0-RC1
- Freeform Version: 4.0.0-beta.3
- Freeform Edition: any
- Fresh Install or Upgrade: fresh

**Additional context**

`composer.json`
```json
{
  "require": {
    "craftcms/cms": "4.0.0-RC1",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.0.17"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/craftcms/cms.git"
    }
  ]
}
```

**Comment by kjmartens** [comment]
Hi @tomdavies, can you adjust the following line and try updating again?

  "craftcms/cms": "4.0.0-RC1",

To:

  "craftcms/cms": "^4.0.0-RC1",

Let me know if that resolves the issue. Additionally, you might also need to delete the `vendor` directory before running the update as well. 🙂

**Comment by tomdavies** [comment]
@kjmartens can confirm this is resolved by blowing away `vendor/` and setting "craftcms/cms": "^4.0.0-RC1", thanks!

Not sure if it's relevant but might be worth bearing in mind that users who update via the CP end up with locked version numbers by default (or at least they did under Craft 3)

**Comment by kjmartens** [comment]
Thanks for your feedback @tomdavies. We are working on a solution that might resolve or workaround this particular issue. The dilemma is that we use the `phpoffice/phpspreadsheet` dependency to enable Excel exporting, and they are stuck at v1 and v2 support, but not v3 of `psr/simple-cache`. Craft 4 added support for another library which ultimately indirectly looks for v1, v2 or v3 support of `psr/simple-cache`, so this is a new issue that affects anyone updating via CP. We may have to temporarily disable Excel export in Freeform 4 (to remove the `phpoffice/phpspreadsheet` dependency) in favor of having a smoother upgrade/install for all customers. In the meantime, we're seeing if there's another Excel library we can use instead. 🙂
