### ISSUE TITLE
[4.0.0-beta] Can't complete feature tour when allowAdminChanges = false

### ISSUE THREAD

**Issue by tomdavies** [solspace/craft-freeform#328]
**Describe the bug or issue you're experiencing**

As of FF `4.0.0-beta.3` It is not possible to complete the feature tour in the form editor UI when `allowAdminChanges` = `false`, because FF tries to write the completion state to Project Config

**Steps to reproduce**

1. Create new install
2. Set `'useProjectConfig' => true` and `'allowAdminChanges' => false`
3. Create a new form
4. Try to dismiss/skip the tour
5. 500 err shown in flash and following in web.log:

```log
2022-04-28 12:55:17 [web.ERROR] [yii\base\NotSupportedException] Changes to the project config are not possible while in read-only mode. {"memory":4571392,"exception":"[object] (yii\\base\\NotSupportedException(code: 0): Changes to the project config are not possible while in read-only mode. at /path/to/webroot/vendor/craftcms/cms/src/services/ProjectConfig.php:493)"}
```

**Expected behavior**

I can skip the tour in any environment

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.0-RC1
- Freeform Version: 4.0.0-beta.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Comment by kjmartens** [comment]
Thanks for reporting this, @tomdavies. It might be a tricky one to fix since this is a limitation of Project Config with `'allowAdminChanges' => false`, but we'll work on a solution to resolve this.

**Comment by tomdavies** [comment]
Maybe just don't show the tour when `'allowAdminChanges' => false` ?

**Comment by kjmartens** [comment]
Yes, that is very likely what we'll end up doing. 🙂

**Comment by tomdavies** [comment]
Context for how I hit this, so that it doesn't seem like I'm just _trying_ to find bugs

- I've used FF before, didn't need a tour
- Pushed change adding FF to live so that I could build a form out there (it's a complex one, and I didn't want to have to do it twice)
- Hit the form builder and end up with an non-dismissable tour getting in the way when I try to click btns.
- (Fixed it by setting the bit locally and deploying, but not obvious until you dive the logs what's happening)

**Comment by kjmartens** [comment]
This is addressed in beta 5 of Freeform 4 🙂
