### ISSUE TITLE
Prechecked default checkbox not showing on front end

### ISSUE THREAD

**Issue by acres42** [solspace/craft-freeform#329]
**Describe the bug or issue you're experiencing**
When clicking a checkbox to set as a default in FreeForm Pro 3.13.7, the checkbox does not show on the front end. _See Image under Additional Context_
Dumping out the response shows that the boolean is always set to "false"
`["checked":"Solspace\Freeform\Library\Composer\Components\Fields\DataContainers\Option":private]=> bool(false)`

**Steps to reproduce**

1. Create a form with check boxes
2. Click on a checkbox in the Freeform plugin to set as default
3. Dump the response
4. Checkbox boolean is always "false"

**Expected behavior**
When a checkbox is clicked in the form, expect to see a checkmark in the checkbox, and for a dump to show that it is "true".

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.37
- Freeform Version: 3.13.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Dump of settings coming through:
`object(Solspace\Freeform\Library\Composer\Components\Fields\DataContainers\Option)#2208 (3) {
  ["label":"Solspace\Freeform\Library\Composer\Components\Fields\DataContainers\Option":private]=>
  string(5) "test3"
  ["value":"Solspace\Freeform\Library\Composer\Components\Fields\DataContainers\Option":private]=>
  string(5) "test3"
  ["checked":"Solspace\Freeform\Library\Composer\Components\Fields\DataContainers\Option":private]=>
  bool(false)`

Images:
<img width="2283" alt="Screen Shot 2022-04-28 at 10 12 05 AM" src="https://user-images.githubusercontent.com/3231614/165776964-52e76b0b-8c99-4853-8f2d-eb14ffa671de.png">

**Comment by kjmartens** [comment]
Hi @acres42,

Sorry for the trouble you're experiencing. I can duplicate this in my testing as well. Thanks for reporting it.

We'll get a fix out for this soon. 🙂

**Comment by kjmartens** [comment]
Hi @acres42, this should be resolved in Freeform 3.13.8 now. 🙂
