### ISSUE TITLE
Unable to overide 

### ISSUE THREAD

**Issue by mauricioarangoosorio** [solspace/craft-freeform#333]
### Describe the bug or issue you're experiencing

I'm not sure if anyone has encountered this, or if this is an error on my part. I added a hidden field with a custom value on a twig template:
```overrideValues: { inquiry: "hello" },```

The form renders the hidden field and its value without issues:
```<input class="ma-form-control" name="inquiry" type="hidden" id="form-input-inquiry" value="hello">```

But inside a notification template, I get an empty value for the hidden field. As if the form were not sending the hidden field along the rest of the fields. 

The attachment shows the output of that hidden field inside the notification template . 

if I add a default value in the form builder, it is not overridden either.

![Screen_Shot_2022-05-01_at_2-1 54 08_PM](https://user-images.githubusercontent.com/41710299/166327726-232b8a0e-a541-4d61-b0d3-1d210e5dd996.jpg)
_at_2.54.08_PM.jpg)

###  Steps to reproduce it

* Add a hidden field to a form
* Add an override in a twig template where the form is being rendered 
* Try to read the value of this hidden input in a notification template 

### Expected behavior
I should be able to read the value entered in the override

### Craft & Plugin Info (please complete the following information):

    Craft Version: Craft Solo 4.0.0-RC2
    Freeform Version: 4.0.0-beta.4
    Freeform Edition: lite
    Ray version 2
    Feedme Version 5 beta 2
    Redactor Version 3 beta 2

###    Fresh Install or Upgrade: 
upgrade from previous V4 beta releases

**Comment by kjmartens** [comment]
Sorry for the trouble @mauricioarangoosorio. In my testing, I can see that it seems regardless of what is specified (and how it's done), data is not stored in the database for Hidden and Invisible field types. Additionally, while email notifications will include the default value specified in the form builder for these fields, they do not include the value set in the `overrideValues` parameter.

We will work on a fix for this shortly. 🙂

**Comment by mauricioarangoosorio** [comment]
Thank you so much. It is good to know you guys are so speedy with these issues.

**Comment by kjmartens** [comment]
This is now resolved in Freeform 4.0.0-beta.6 🙂
