### ISSUE TITLE
Unable to change year when using Flatpickr.js

### ISSUE THREAD

**Issue by mediabeastnz** [solspace/craft-freeform#334]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. create a date field and use freeform's built in date picker
2. view on the frontend to see that year dropdown is missing

**Expected behavior**
By default Flatpickr.js looks to include the year picker on it's examples.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.15
- Freeform Version: 3.11.4.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: n/a

**Additional context**

**Comment by kjmartens** [comment]
Hi @mediabeastnz, I'm not seeing this in my testing. When I check the date picker, it correctly shows an up/down arrow on the year (and the ability to type in my own year). Is this not the case for you?

Perhaps try updating to the latest Freeform (3.13.x) and see if that helps. If not, can you let me know which browser and version you're using? And if there are any JS errors in the console, let me know as well. 🙂

**Comment by mediabeastnz** [comment]
We'll try updating :)

**Comment by mediabeastnz** [comment]
Hey @kjmartens, we tried upgrading to Craft 3.7.42 + FreeForm 3.13.9 but still the year isn't displaying.

We've tried on all modern browsers. We also can't see any markup being generated for the year element but the month works OK.

For reference, this is the form  - https://theborough.nz/functions-and-events

**Comment by mediabeastnz** [comment]
Closing. It was a CSS inheritance issue.
