### ISSUE TITLE
Equals sign "=" causing error in text fields when using Quick Export

### ISSUE THREAD

**Issue by tylor** [solspace/craft-freeform#335]
**Describe the bug or issue you're experiencing**

This is a super minor bug, and kind of a hilarious quirk that took a little while to track down.

We have a form set up that's using a text field to collect phone numbers, and after a little while we noticed the Quick Export to Excel stopped working. Turns out someone had submitted an international phone number, but instead of a leading '+' they erroneously entered an '='. When you quick export to Excel, the leading '=' is interpreted as a formula by PhpSpreadsheet and the phone number wasn't a valid formula, and whole thing failed.

We're probably better off to use the phone number field to validate the input, and export to CSV works just fine.

**Steps to reproduce**

1. Create a new form
2. Create a new text field, add a submit button
3. Put the form on a page
4. Submit the form with "=555 555 5555"
5. Go to submissions, select the form, click Quick Export. Export as: Excel and make sure the field is selected
6. Errors out with PhpOffice\PhpSpreadsheet\Calculation\Exception

**Expected behavior**

The Excel file is downloaded. User input in a text field is not executed as an Excel formula.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.26
- Freeform Version: 3.13.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the delay, @tylor. We'll check into this one shortly. 🙂

**Comment by kjmartens** [comment]
This is now fixed in Freeform 3.13.12 🙂

**Comment by tylor** [comment]
No worries, thanks!
