### ISSUE TITLE
Unable to create new fields - "Total field limit reached"

### ISSUE THREAD

**Issue by sarlahooda** [solspace/craft-freeform#336]
"craftcms/cms": "3.7.38"
"solspace/craft-freeform": "3.13.7"

<img width="1595" alt="Screenshot 2022-05-05 at 10 13 17" src="https://user-images.githubusercontent.com/90087260/166885528-cfb946bb-f778-4dcd-b42b-9dab3cc4bfa1.png">

Is there a way to solve this issue? We are also having problem with storing the submissions to the database. I tried to follow the steps mentioned here - https://github.com/solspace/craft-freeform/issues/330. But this has not worked for me so far. 

Is there an easier way to increase the field limit and fix the data storage issue?

**Comment by kjmartens** [comment]
Hi @sarlahooda,

Sorry for the trouble. Out of curiosity, how many fields do you currently have for your site? 🙂

**Comment by sarlahooda** [comment]
Hi @kjmartens 

249 in `craft_freeform_fields` table - 

<img width="489" alt="Screenshot 2022-05-06 at 09 51 37" src="https://user-images.githubusercontent.com/90087260/167090359-1870f4c3-434a-41cd-bd12-9fed679929aa.png">
