### ISSUE TITLE
Cannot integrate Constant Contact

### ISSUE THREAD

**Issue by mauricioarangoosorio** [solspace/craft-freeform#355]
**Describe the bug or issue you're experiencing**
I seted up all the required information for the Constant Contact integration. 
I am able to do the Oauthorization, however, when the page redirects I get a YII error.
I'm not sure if this is a Freeform bug, an issue with Constant Contact, or if I'm doing something wrong.

**Steps to reproduce**

1. Start a Constant Contact integration, enter all the required information
2. Do the authorization.
3. You should be taken to Constant Contact to login
4. After login in Constant Contact the page is redirected to Freeform's generated URL. The following errors are displayed:
```
[HTTP 400 – Bad Request](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#400) – [yii\web\BadRequestHttpException](http://www.yiiframework.com/doc-2.0/yii-web-badrequesthttpexception.html)

Invalid data received for parameter "id" n /webroot/staging-916b08bf59/release/deployment_50_a2debb8d/vendor/yiisoft/yii2/web/Controller.php at line 174 
```

The return URL is this (it has been slighly modified for privacy): 
`https://staging.xxxxx.com/office/freeform/settings/mailing-lists/crosbystreetstudiosmaster?code=1Ej4LKF8yG303xdHbv1Dw0EnbOQjg9VCB7YZAXEsI_M&state=i9m9hmm0k3cim7l7rivnigh54l`

**Expected behavior**
The integration process should proceed without any Yii errors.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.0.3
- Freeform Version: 4.0.0-beta.8
- Freeform Edition: Paid Pro version
- Fresh Install or Upgrade: Upgrade from previous beta versions

**Additional context**

**Comment by kjmartens** [comment]
Hi @mauricioarangoosorio,

I can reproduce some issues with this as well. We are investigating what the problem might be and will get back to you.

Sorry for the trouble.

**Comment by mauricioarangoosorio** [comment]
thank you so much!! Yes, indeed, it is workng now. I appreciate it a lot!!
