### ISSUE TITLE
[4.x] TypeError in CP submissions

### ISSUE THREAD

**Issue by jerome2710** [solspace/craft-freeform#359]
**Describe the bug or issue you're experiencing**
The XHR to find submissions in CP's `/admin/freeform/submissions` will fail if there are no forms or submissions yet. `array_values($formHandleToIdMap)` expects an array, but `$formHandleToIdMap` will be `null` if there are no forms/submissions.

```
{
    "error": "array_values(): Argument #1 ($array) must be of type array, null given",
    "exception": "TypeError",
    "file": "/app/vendor/solspace/craft-freeform/packages/plugin/src/Elements/Db/SubmissionQuery.php",
    "line": 214,
    "trace": [
        {
            "file": "/app/vendor/solspace/craft-freeform/packages/plugin/src/Elements/Db/SubmissionQuery.php",
            "line": 214,
            "function": "array_values"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/elements/db/ElementQuery.php",
            "line": 1258,
            "function": "beforePrepare",
            "class": "Solspace\\Freeform\\Elements\\Db\\SubmissionQuery",
            "type": "->"
        },
```

**Steps to reproduce**

1. Have no submissions or forms yet
2. Navigate to `/admin/freeform/submissions`

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.3
- Freeform Version: v4.0.0-beta.8
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Comment by kjmartens** [comment]
Thanks @jerome2710. We'll get this fixed shortly. 🙂
