### ISSUE TITLE
403 status unless logged in as admin

### ISSUE THREAD

**Issue by anchovy** [solspace/craft-freeform#364]
**Describe the bug or issue you're experiencing**
We've recently upgraded freeform (and craft) to the latest versions and the server to php 8.0 and now when I submit a form, unless I'm logged in as admin I get a 403 error?

**Steps to reproduce**

1.
2.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: latest
- Freeform Version: latest
- Freeform Edition: pro 
- Fresh Install or Upgrade: upgrade

**Additional context**

**Comment by kjmartens** [comment]
Can you please provide more information about your setup? By "latest" are you referring to Freeform 3.13.11 or 4.0.0-beta.11, etc? Which version did you upgrade from? Are you seeing any detailed errors in the console or logs, etc? 🙂

**Comment by TheCohorts-reuben** [comment]
Hi - Sorry, upgraded from:
PHP: 7.4
Craft Pro: 3.6.17
Freeform Pro: 3.11.9
composer: 1

PHP:  8.0.19
Craft Pro: 3.7.44
Freeform Pro: 3.13.11
Composer: 2

Mysql stayed the same at: 5.7.38

There are no errors/log file in storage/logs/freeform.log & no console errors either... super odd.

**Comment by kjmartens** [comment]
Ok that makes a big difference. Can you change the action to `freeform/submit` and see if that resolves the issue? If not, you may also need to ensure the payload is added as well (but this could depend on how you currently have this implemented).

**Comment by anchovy** [comment]
Hi @kjmartens - changing to `freeform/submit` (or totally removing the action so it submits to the current url) fixes the issue; no 403 on submit now...  But I've also had to change to the Freeform > Settings > Form Behavior > Freeform Session Context to _Using PHP's sessions_ as per #236
