### ISSUE TITLE
Predefined subscription plans not showing option titles in form builder

### ISSUE THREAD

**Issue by terryupton** [solspace/craft-freeform#369]
**Describe the bug or issue you're experiencing**
When trying to show Predefined subscription plans in the back-end form builder, it appears to pull them through but the option names/titles are blank. 

<img width="522" alt="Screenshot 2022-06-14 at 15 11 12" src="https://user-images.githubusercontent.com/5698596/173599141-0137eb10-9aa7-4226-91c0-292927bd11d6.png">

If I inspect the code, it looks like the list is populated but the option/title is missing. 
<img width="771" alt="Screenshot 2022-06-14 at 15 16 58" src="https://user-images.githubusercontent.com/5698596/173599786-85f40e79-d468-4cc3-a01d-45de9454acf1.png">

**Steps to reproduce**
1. Create a form
2. Add a payment facility/integration
3. Choose 'Predefined subscription plan' as the payment type
4. Click the refresh plans
5. Click on the 'choose a subscription plan'
6. The list seems to populate but without any titles.

**Expected behaviour**
Should show a list of subscription plans setup in side Stripe.

**Comment by kjmartens** [comment]
Hi @terryupton,

I can duplicate this in my testing as well when the subscription/product is created directly inside Stripe and does not contain a **Price Description**. What you'll want to do is be sure to fill this out in the advanced options when creating new ones:

<img width="780" alt="Screen Shot 2022-06-15 at 1 31 28 PM" src="https://user-images.githubusercontent.com/1821674/173900819-4a49fb85-a2ee-4832-8541-d1e76737e978.png">

Or to update existing ones, go to **Products**, then click the `...` at the right of the product, select _Edit Product_. Then scroll down to _Price information_, look for _Additional options_ and enter the **Price description** there.

Once you've added this to the subscriptions, be sure to click the **Refresh Plans** button inside the form builder.

That said, I was thinking that we could perhaps have Freeform grab the **Product Name** value from Stripe if the Price description doesn't exist, but one problem is that a product can have multiple prices/intervals, so it's actually important that Freeform looks at the Price description. Perhaps there's still a way for us to have Freeform give these options unique labels based on other Stripe data. I've made a note about that now. 🙂
