### ISSUE TITLE
Suggestion - change the default placeholder for email templates

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#377]
**Describe the bug or issue you're experiencing**

Only a really minor one, but the default suggested folder name for email templates is `freeform_emails/`. That will make the templates visible to the public by default. Can we change that to something starting with an underscore like `_freeform_emails/`?

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1250017/175282117-a3df579a-e1fe-48cd-a70f-4e3dc8b16392.png">

**Comment by darylknight** [comment]
Follow up issue - nothing happens below this section unless you go and manually create the folder. I know that kind of makes sense, but it might be worth noting in this section that you need to create the folder to see the rest of the options.

**Comment by kjmartens** [comment]
Thanks for your feedback @darylknight. I've committed some improvements to these settings now. They'll be in the next version of Freeform 4. :)
