### ISSUE TITLE
Can't Install Fresh on Craft 4 via composer, but works with CP

### ISSUE THREAD

**Issue by CreateSean** [solspace/craft-freeform#381]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. copied composer command from plugin store `composer require solspace/craft-freeform && php craft plugin/install freeform`
2. get the following error:

```
  Problem 1
    - solspace/craft-freeform[3.13.0, ..., 3.13.13] require craftcms/cms ^3.4.0 -> found craftcms/cms[3.4.0-beta.1, ..., 3.7.45.2] but it conflicts with your root composer.json require (^4.0.0).
    - Root composer.json requires solspace/craft-freeform ^3.13 -> satisfiable by solspace/craft-freeform[3.13.0, ..., 3.13.13].
```

My composer.json file has the following:     `"craftcms/cms": "^4.0.0",`

**Expected behavior**
it installs as expected

However installing via the CP works.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.4
- Freeform Version: 4.0.0-beta.12
- Freeform Edition:
- Fresh Install or Upgrade: Freesh install

**Additional context**

**Comment by kjmartens** [comment]
@CreateSean While Freeform is in beta, you'll likely need to specify the version specifically when running that command:

`composer require solspace/craft-freeform:4.0.0-beta.12 && php craft plugin/install freeform`

You can also update your `composer.json` file and run `composer update` instead:

```
"require": {
   "craftcms/cms": "^4.0.0",
   "vlucas/phpdotenv": "^5.4.0",
   "solspace/craft-freeform": "^4.0.0.beta.1"
},
```
