### ISSUE TITLE
Freeform JS plugin not detecting all dynamically added form elements

### ISSUE THREAD

**Issue by nielsquirynen** [solspace/craft-freeform#385]
**Describe the bug or issue you're experiencing**
In our project we're creating Freeform form elements dynamically by iterating over a dataset using AlpineJS.
We noticed however that the Freeform JS plugin is not picking up on these dynamically added elements.

When digging through the Freeform JS source code, I noticed that the MutationObserver that tries to pick up on these dynamically added forms does not account for child elements. It only checks if the added element itself is a `form[data-freeform]` element.
A solution would be to recursively iterate over the added node and it's child nodes to pick up on these newly added form elements.

**Steps to reproduce**
1. Enable the Freeform JS plugin
2. Create a Freeform form and enable AJAX form submits
3. Add a Freeform form element in a nested AlpineJS for-loop element

**Expected behavior**
Submitting the dynamically added form triggers the AJAX validation.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.37
- Freeform Version: 3.13.12
- Freeform Edition: Pro
- Fresh Install or Upgrade: fresh install

**Additional context**
I've created a demo in codepen with the current MutationObserver and an additional MutationObserver that walks over it's children (potential fix):
https://codepen.io/LunarNielsQ/pen/jOzOjry

**Comment by kjmartens** [comment]
Sorry for the delay @nielsquirynen. I'm having a developer check into this. We'll respond to you soon. 🙂

**Comment by kjmartens** [comment]
This should now be resolved in Freeform v3.13.15. 🙂
