### ISSUE TITLE
conditional rules not working as expected: TypeError: Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by FrDH** [solspace/craft-freeform#388]
**Describe the bug or issue you're experiencing**
We have a conditional rule that requires a field to have a specific value, when this field also has its own conditional rule, the following error appears in the console (frontend) and the field is always shown (which makes sense since there's a js error):
plugin.js?v=xxx Uncaught TypeError: Cannot read properties of null (reading 'toLowerCase')
    at e.getInputType (plugin.js?v=xxx)
    at plugin.js?v=xxx
    at Array.forEach (<anonymous>)
    at plugin.js?v=xxx
    at NodeList.forEach (<anonymous>)
    at e.reload (plugin.js?v=xxx)
    at new e (plugin.js?v=xxx)
    at plugin.js?v=xxx
    at Array.forEach (<anonymous>)
    at r._initHandlers (plugin.js?v=xxx)

**Steps to reproduce**
1. create a new form with 3 fields (field A, B and C)
2. create a conditional rule for field B, only showing it when field A is not empty
3. create a conditional rule for field C, only showing it when field B is not empty

**Expected behavior**
At first only field A should be visible
After typing something in field A, field B should appear.
After typing something in field B, field C should appear.

**Craft & Plugin Info (please complete the following information):**
- Craft Version: 3.7.44
- Freeform Version: 3.13.14
- Freeform Edition: PRO
- Fresh Install or Upgrade: Upgrade

**Additional context**
Probably just an issue with the js error, hope it can be fixed :)

**Comment by FrDH** [comment]
Sorry, our form is a bit different, here's a more details description:

Field A is a radiobutton group (options: "yes" and "no")
Field B is a multiple select list (options: "x", "y", "z"), should only be visible if field A is "yes"
Field C is a textaria, should only be visible if field A is "yes" and field B contains "z".

The problem appears when I add the second rule for Field C (when field B should contain "z")

**Comment by kjmartens** [comment]
This should now be resolved in Freeform v3.13.15. 🙂
