### ISSUE TITLE
Confusing translation (in Dutch) for the any / each toggle in conditional rules

### ISSUE THREAD

**Issue by FrDH** [solspace/craft-freeform#390]
**Describe the bug or issue you're experiencing**
Not sure if this is a freeform or craft translation, but in the any / each toggle in conditional rules both words are translated to a word that essentially means the same.
![Schermafbeelding 2022-07-08 om 11 22 47](https://user-images.githubusercontent.com/1387163/177961771-98534a73-3c5d-4236-8634-42b2e403e3eb.png)
![Schermafbeelding 2022-07-08 om 11 22 41](https://user-images.githubusercontent.com/1387163/177961782-1b0578ba-25ed-4c51-8362-67b31c743e0e.png)

"alle" is Dutch for "all"
"elk" is Dutch for "each"

A better translation would be:
"een" is Dutch for "a" or "one"
or more acurate but way longer:
"ten minste één" is Dutch for "at least one"

**Steps to reproduce**
1. Create a site in Dutch :)
2. Create a form with conditional rules

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.44
- Freeform Version: 3.13.14
- Freeform Edition: PRO
- Fresh Install or Upgrade: fresh install

**Additional context**

**Comment by kjmartens** [comment]
Thanks @FrDH. We'll have this fixed for the next release. 🙂
