### ISSUE TITLE
pardot v5 crm Integration - hidden input value of 0

### ISSUE THREAD

**Issue by shpfive** [solspace/craft-freeform#391]
**Describe the bug or issue you're experiencing**

I setup a form with a crm integration to pardot. 
One of the requried fields by Pardot is score. In my Form i setup a hidden input with a default value of 0 and linked it accordingly.
When submitting the form i get an error from Partdot because i submitted an invalid value for score.
In the log i can see that the score url param is in the request url but it is empty.

`&profile=Default&score=&zip=`

`resulted in a '400 Bad Request' response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rsp stat=\"fail\" version=\"1.0\">\n <err code=\"29\">Invalid value specified for sco (truncated...)\n"} []`

In the submissions in the craft backend the value is 0.

**Steps to reproduce**

1. setup a pardot crm integration
2. setup a hidden field with default value of 0 

**Expected behavior**

the request param should be 0 not empty

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.47.1
- Freeform Version: 3.13.14
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Hi @shpfive,

I'm very sorry for the delay. Pardot is one of the more difficult integrations for us to troubleshoot and support as they do not offer any trial or sandbox accounts for developers like us. I can see that perhaps Freeform is looking at `0` as NULL instead of `0`. At any rate I will check with a developer and see if this is a quick thing we can account for. 🙂

**Comment by kjmartens** [comment]
Sorry for the delay @shpfive,

I checked with a developer and he says Freeform isn't doing anything with the values, so they should go through as `0` if set so. This is for both Pardot and Salesforce. Is it possible you are doing something additional on your end / Pardot side of things like rules, etc? 🙂

**Comment by shpfive** [comment]
Hi @kjmartens,
no problem at all. Thanks for checking. It seems like it was an issue with Pardot to Salesforce sync wich then gave back the error message to the freeform integration.
Thanks for your help

**Comment by kjmartens** [comment]
Thanks @shpfive 🙂
