### ISSUE TITLE
Freeform seems to be looking for email templates even if "Database" is selected

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#394]
Freeform is set to use database for notification templates:

![image](https://user-images.githubusercontent.com/1250017/179036960-f3ddaf06-6fe2-4216-a71f-4b3b9b6569db.png)

When I go to a form and don't have any database notifications created, I try to create one from the form edit screen and get this:
![image](https://user-images.githubusercontent.com/1250017/179036920-dcce4a47-0235-4aad-8060-71a1bcfddbb5.png)

Craft 4.1.4.1
Freeform 4.0.0-beta.15.1

**Comment by darylknight** [comment]
Thank you. If I try to create an email template from control/freeform/notifications/database/new, I get the error below. I assume it's the same thing.

![image](https://user-images.githubusercontent.com/1250017/179158751-fb41ee74-fcce-4f1c-a0e0-ea7d5dc95a90.png)

**Comment by kjmartens** [comment]
Sorry for the trouble @darylknight. We have made a fix in the repo and will get a new version out shortly. 🙂

**Comment by darylknight** [comment]
Nice one, thanks!

**Comment by darylknight** [comment]
Is there a way I can install a dev branch or something with this fix? A client site currently has no notifications

**Comment by kjmartens** [comment]
This is now fixed in v4.0.0-beta.16. Thanks for your patience. 🙂

**Comment by darylknight** [comment]
Excellent, thank you! Yeah, that's working now.
