### ISSUE TITLE
Freeform 4.0.0 Split Submissions Database Migration Bug 

### ISSUE THREAD

**Issue by kiwidood** [solspace/craft-freeform#395]
**Describe the bug or issue you're experiencing**

After migrating the database from solspace/craft-freeform 3.13.14 to 4.0.0-beta.15.1, certain forms submission lists cannot be viewed.

Line 226 in the migration:
craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php

Uses:
`$handle = StringHelper::toSnakeCase($handle);`

However line 226 in the file:
craft-freeform/packages/plugin/src/Elements/Submission.php

Uses:
`$handle = CraftStringHelper::toKebabCase($handle, '_');`

For a field with name postalDetails4, this produces inconsistent results (i.e. postal_details_4 in the table and postal_details4 in the query). When trying to access the submissions page you would get an error such as: Column not found: 1054 Unknown column 'fc1.postal_details4_145'

Updating line 71 in the migration to this fixes the issue:
`$handle = StringHelper::toKebabCase($handle, '_');`

**Steps to reproduce**

1. Start on Freeform 3.3.14
2. Create a field in a form named "postalDetails4"
3. Run database migration
4. Try and access the submissions page for the form

**Expected behavior**

Consistent table names and query in order to show submissions

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 4.1.4.1
- Freeform Version: 4.0.0-beta.15.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kiwidood** [comment]
> Hi @kiwidood. I'm very sorry about this. We've made a fix in the repo (can try updating to `dev-master` if you like) and we will test more thoroughly again and release an update shortly. 🙂

Great, thank you very much!

**Comment by kjmartens** [comment]
This is now fixed in v4.0.0-beta.16. 🙂
