### ISSUE TITLE
Suggestion: Host dependencies locally instead of linking to CDNs

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#403]
Trying to access any Craft 3's Freeform dashboard this morning is taking over a minute to show the page. It looks like this is because it's waiting to load resources from https://unpkg.com/tippy.js@6 which is either temporarily unavailable, or doesn't exist anymore. [scale.css](https://unpkg.com/tippy.js@6/animations/scale.css) is returning a 520 error.

Can I suggest that these are included as part of Freeform's build process instead of linking to external websites?

**Steps to reproduce**

1. Go to the dashboard in Freeform 3.x
2. Wait for 40 seconds for it to time out

![image](https://user-images.githubusercontent.com/1250017/180403868-105252ed-10a4-4964-97ec-a6d164c4c980.png)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.47.1
- Freeform Version: 3.13.15
- Freeform Edition: Pro

**Comment by AbbeyDesign** [comment]
I've been having the same issue. Slowness and a lot of 500 errors on what should have been simple pages. Could not figure out why but then I noticed it was calling into unpkg.

**Comment by kjmartens** [comment]
Sorry for the trouble. We're going to fix this shortly. 🙂

**Comment by kjmartens** [comment]
This has been fixed in the latest versions of Freeform now 🙂
