### ISSUE TITLE
CSV export of submissions is not correctly exporting Japanese content

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#408]
**Describe the bug or issue you're experiencing**

We run a multisite website which has a regional site for Japan in Japanese. Our client there contacted my to say that the CSV export from Freeform of the contact form submissions has garbled all the Japanese content: "All the non-alphabet words do not make sense."

Below is the content of the CSV file they sent me, with email addresses removed:

```
ID,IP,Date Created,Title,"姁E,吁E","施設名／会社吁E,診療科�E所属（医療従事老E�E方�E�　支店�E営業所名（代琁E���E方�E�E",Email,お問ぁE��わせ冁E��,"備老E,同意する""",
177731,,2022/7/21 20:43,2022/7/21 20:43,"山丁E,侑吾""",京都大学,"循環器冁E��E,[email address removed]""","弊社拁E��老E��よる面諁E�E打ち合わぁE,RADIANZに関して、京都大学の拁E���E方に、山下にまで連絡をとって頂けれ�E幸ぁE��ござぁE��す。今後�E使用めE��用に関しての御相諁E��す、E",Yes,
177732,,2022/7/22 1:53,2022/7/22 1:53,"介巁E,重幸""",サンセイ医機株式会社,福島営業所,[email address removed],製品�E詳細惁E��,"福島第一痁E��へ初めてフェルメチE��E�EVGW1430NS1を使用頂きましたが、弊社販売にあたり商品登録する忁E��あり、商品登録に忁E��な弊社賁E��に記載頂きたくお願いするにあたり、御社のFAX番号を教えて頂きたくお願いぁE��します。（フェルメチE��様に上記連絡した所、コーチE��ス様に依頼してくれとの事でした�E�E
販売ルート�EチE��コ株式会社→サンセイ医機�E第一痁E��となっております、E
よろしくお願いぁE��します、E,Yes"""
```

Although I don't speak Japanese, I can see that there are bunch of � symbols in there that clearly aren't Japanese characters. Are you able to shed any light on what might be happening? I can see that the submissions appear to be stored correctly in the control panel:

![image](https://user-images.githubusercontent.com/1250017/180940232-15b0f07e-be87-4a74-a392-78901fe1c100.png)

We have the Intl extension installed correctly

![image](https://user-images.githubusercontent.com/1250017/180940362-5c7d9b0d-8044-495a-a21c-d099aac2b52c.png)

**Steps to reproduce**

1. Receive form submissions in Japanese
2. Export those submissions via CSV

**Expected behavior**
CSV export should contain the correct Japanese characters

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.48
- Freeform Version: 3.13.15
- Freeform Edition: Lite

**Comment by kjmartens** [comment]
Hi @darylknight,

Sorry for the delay. I can confirm this behaving similarly in my testing. I've made a note about it and we'll see what we can do to resolve it. 🙂

**Comment by darylknight** [comment]
Thanks Kelsey, sounds good. (Sorry I've been on holiday for the last couple of weeks). Let me know what you find out.

**Comment by kjmartens** [comment]
Hi @darylknight,

We're investigating this issue again, and we cannot duplicate the issue. I was able to once before, but now I can't. I have tried doing this so many different ways, but I can't get it to happen anymore. Is this still happening for you? Are you able to check the encoding of the file? (can run `file -i file_name.csv` in terminal, etc)

Thanks 🙂

**Comment by darylknight** [comment]
Uhh actually it looks like it might be working ok on my end too. Weird. I'm now running the latest versions of Craft 4 and Freeform 4, and I can't find any � symbols in the latest export file.

I'll get in touch with the client to get them to confirm, but I think we can close for now. Thank you again!
