### ISSUE TITLE
Urgent: All forms including plugin.js on a multisite install are throwing a 404 error

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#409]
**Describe the bug or issue you're experiencing**

I've just discovered that all of our forms on a multisite are broken because plugin.js is throwing a 404 error. Example URLs of forms (see console errors):

1. https://cordis.com/ja/form
![image](https://user-images.githubusercontent.com/1250017/180944430-22320251-6827-41e8-b313-d9e9624effdf.png)

2. https://cordis.com/na/radial-360-contact
![image](https://user-images.githubusercontent.com/1250017/180944681-e964b14e-1af2-4767-9ad7-de035aeb1a1d.png)

3. https://cordis.com/na/products/access/cardiology/rain-sheath-transradial-thin-walled-introducer
![image](https://user-images.githubusercontent.com/1250017/180944505-55906022-ba16-4139-be07-1a51bb5da267.png)

**Setup - Form settings:**
![image](https://user-images.githubusercontent.com/1250017/180943836-f829c872-7ff6-4de1-b5a9-132fffd5cfb7.png)

**Setup - Site Settings**
Each site has a different language code as part of it's base URL:
![image](https://user-images.githubusercontent.com/1250017/180944270-c47fad31-e4e1-4f87-a067-efe3aceaa009.png)

If I actually go to the URLs they link to, the file does exist. I don't know why it's throwing a 404 error on the front end. It appears to be working on my local install. Only thing I can think of is something to do with the routing of the multisite stuff. The two URLs (for NA and JA respectively) are:
https://cordis.com/na/freeform/plugin.js?v=bf2b5aeb65e617b4a75a3d350ab9df79917ce00b
https://cordis.com/ja/freeform/plugin.js?v=bf2b5aeb65e617b4a75a3d350ab9df79917ce00b

All forms are using the default Bootstrap 5 template.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.48
- Freeform Version: 3.13.15
- Freeform Edition: Lite

**Comment by darylknight** [comment]
Closing this - I managed to fix it by changing the Freeform Script Insert Type to "As Files" after googling for "freeform plugin.js" on discord and discovering [this discussion](https://github.com/solspace/craft-freeform/discussions/224#discussioncomment-1529523)

![image](https://user-images.githubusercontent.com/1250017/180951867-8071df8e-6482-407f-aec6-108ff83f2dd6.png)

However - while I'm here, can I point out that it's really unclear -why- anyone might be having issues with the default method of static URLs? I've had to change this on a site in the past, and I don't really understand why, or what the implications are of doing so.

**Comment by kjmartens** [comment]
Hi @darylknight,

Sorry for the trouble you were experiencing. This has something to do with server rules you have applied to JS and CSS files to see if they are actual files. The default for Freeform is to load its scripts as static URLs, which becomes a problem in this case.

To resolve this issue, we recommend customers fine-tune those checks or switch the **Freeform Script Insert Type** setting (Craft CP -> Freeform -> Settings -> Form Behavior) to **As Files** as you have done. 🙂 

In Freeform 4, we have additional checks in place to automatically set this to **As Files** upon installation if Freeform detects you have your server set up that way. If Freeform is already installed, Freeform's settings and diagnostics pages show a warning to switch to **As Files**. 🙂

**Comment by darylknight** [comment]
Sounds great, thanks Kelsey :)
