### ISSUE TITLE
Form is submitting twice, 1 sec apart

### ISSUE THREAD

**Issue by Jones-Lafuente** [solspace/craft-freeform#414]
Currently developing a site and I have two forms on a page, one a contact form with name, email, phione and message, and the other a basic signup form with just email. When testing and logged into the CMS both work perfectly. When testing as a regular viewer of the site (not logged inot the CMS) the contact form is being submitted twice, 1 sec apart. 

Have followed all the documentation, all settings seem to show that a form cannot be submitted by the user clicking twice, am only clicking the one time anyway. 

Am I missing something? I am using Craft CMS 3 and the Postmark mailer for sending emails. Am stumped as it is only happening on the one form and only for those not logged in, which will be everyone viewing the site when live. 

All help appreciated, thanks

Brian

**Comment by kjmartens** [comment]
Hi @Jones-Lafuente,

Sorry for the trouble you're experiencing. I'm wondering if you can try something out for me. Can you [install the demo templates](https://docs.solspace.com/craft/freeform/v3/setup/demo-templates.html) included with Freeform and in the Bootstrap section, try testing the form there. Does the form work correctly there? 🙂 

Also, which exact version of Freeform are you using?

**Comment by joneslafuente** [comment]
Hi kjmartens

I now have it working and it kind of makes sense but not completely sure. I will explain.

The form is a simple four field contact form, it is placed inside a container that sites outside the browser viewport to the right. Is 100% height and position fixed. When the user clicks the contact button the panel slides into view. 

All works fine, the form is submitted. When logged into Craft the submission occurs just the once, if testing as a viewer not logged in then it submits twice. I changed the css to have the form inside the viewport but not displaying and then fade the form into view. This way it works, so is something to do with the original position being outside the viewport?

Any thoughts more than welcome.

Thanks

Brian

**Comment by kjmartens** [comment]
The only thing I can think of would be that the JS you used to make the form slide into view could be affecting the form's JS or something like that. I am also vaguely recalling where a hack needed to be made if trying to load a form inside of a modal loaded by an older Bootstrap library, so it could be something _like_ that.

**Comment by thomasgoemaere** [comment]
Hi,

I'm having a sort like issue.
When submitting the form in a popup / modal it submits multiple times.
What I've noticed is that it has something to do with the reCAPTCHA.
The hidden input tag with the name "g-recaptcha-response" get's added multiple times, each time the modal get's triggered the input tag get's added again so this causes the form to be submitted multiple times cause each hidden input tag triggers a new submit.

Below is a screenshot of the reCAPTCHA hidden tags when opening the same modal multiple times through a button.
The input tag get's injected again and again...

![Schermafbeelding 2022-08-09 om 11 07 24](https://user-images.githubusercontent.com/1284055/183615801-33c31c0d-e75e-41ca-8994-a06c2acdec0c.png)

As I recall the hidden tag should normally be generated only once...

When reverting back to release 3.13.14 everything works fine again.

Thanks for looking in to this,

Kind regards,
Thomas
