### ISSUE TITLE
Reload Form with Success Message doesn't work if query string already exists

### ISSUE THREAD

**Issue by Coysh** [solspace/craft-freeform#415]
**Describe the bug or issue you're experiencing**
Trying to reload a form using the Success Behaviour of "Reload Form with Success Message".
If the form already has URL parameters (i.e. ?utm_source=facebook) then form then reloads with the query string appended (i.e. ?utm_source=facebook?success) which doesn't work.

I've tried reproducing this with the default templates and my own custom one.

**Steps to reproduce**

1.
2.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.48
- Freeform Version: 3.13.15
- Freeform Edition: Pro
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Hi @Coysh. I've tried playing around with this a bit on my end, and everything seems to be okay. Perhaps I am misunderstanding what you're asking or reporting here though. In my testing, the URL doesn't change. I'm curious what your full setup is where you're observing this. Can you provide additional information such as:

- whether you have AJAX enabled or not
- if you have any JS overrides in the template
- what your template code looks like

Thanks 🙂
