### ISSUE TITLE
Internal Server Error after Installing Demo Templates

### ISSUE THREAD

**Issue by prager** [solspace/craft-freeform#417]
**Bug Description**

After installation of demo templates it is not possible to edit a new form via Freeform dashboard. The form created OK, but when attempted to edit the form an Internal Server Error was displayed. The same error was thrown when clicking on Settings->Success Templates.

Settings->Diagnostics indicate that _"Success Templates Directory Path: Not set correctly"_  in `templates/forms/success.twig`. This is the path to previously created and set success template in Settings->Success Templates

**Steps to reproduce**

1. Create a form in Freeform Dashboard
2. Create a Success Template in a custom directory such as `templates/forms/success.twig`. 
3. Enter the template path to Settings->Success Templates
4. Install demo templates via Settings->Demo Templates
5. Click on the form created in # 1 in Freeform Dashboard. That will generate the Internal Server Error
6. Click on the Settings->Success Templates. That will generate the Internal Server Error

**Expected behavior**

No Internal Server Error should be thrown even though the Success Templates Directory Path would be set incorrectly. If that would be the case, a specific error message should be displayed

**Craft & Plugin Info:**

- Craft Version: Pro 4.2.0.2
- Freeform Version: 4.0.0-beta.18 (trial)
- Fresh Install or Upgrade: Fresh install

![err-craft_internal](https://user-images.githubusercontent.com/18473082/182675155-ae117215-3d90-4fa7-8280-36a8b51f5b88.png)

**Comment by kjmartens** [comment]
Hi @prager,

Sorry for the trouble you're experiencing. Can you confirm what value you set for the **Success Templates Directory Path**? If you can't remember or can't access that page, you can view the path in the `project.yaml` Project Config file. The setting you're looking for is `successTemplateDirectory`. A valid value would be something like: `successTemplateDirectory: freeform_success` (path to a directory, not a full path to a file).

Aside from that, I'm curious what the error logged is (for the Internal Server Error). Would you be able to check the Craft logs for it? 🙂

**Comment by prager** [comment]
Thank you @kjmartens for a quick response!

I set the value of `successTemplateDirectory` as you suggested, but the system overwrote it back to `templates/forms/success.twig`.

It looks like I made a mistake of entering in _"Settings->Success Templates"_ the path including the filename such as `templates/forms/success.twig`, which broke the system.

However, I think this error should be handled more properly.

**Comment by kjmartens** [comment]
Ok, glad you were able to get it sorted. In regards to the overwriting issue, it was likely because after updating that value in the project config file, you'll need to go into the Craft control panel and "accept" the changes as well.

At any rate, you're right about Freeform handling this more gracefully. I'll make a note about that and we'll be sure to have that improved. 🙂
