### ISSUE TITLE
Element Connections

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft-freeform#432]
Have a form that uses Element Connections to generate new entries. its nothing too complicated, just mapping 5 fields. Since upgrading, the settings/mapping of those connections is empty when editing the form **BUT** it still creates new entries with the right content in the right place.

- Craft Version: 4.2.1.1
- Freeform Version: 4.0
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by anchovy** [comment]
Seems like the same issue as #427

**Comment by kjmartens** [comment]
This is now resolved in Freeform 3.13.19 and 4.0.3. 🙂
