### ISSUE TITLE
[v3] Uncaught ReferenceError: isHCaptcha is not defined

### ISSUE THREAD

**Issue by jrrdnx** [solspace/craft-freeform#436]
**Describe the bug or issue you're experiencing**
Recently upgraded to v3.13.17, and now when trying to modify existing forms the edit screen is completely blank. The console shows "Uncaught ReferenceError: isHCaptcha is not defined" in file `builder.js`:

![image](https://user-images.githubusercontent.com/4584671/186017867-4c644e96-8a4e-4c6b-9508-3c109d6925fa.png)

- Craft Version: 3.7.51
- Freeform Version: 3.13.17
- Freeform Edition: PRO
- Fresh Install or Upgrade: Upgrade (from 3.11.10)

**Additional context**
This is occurring _only_ on staging and production environments running PHP 7.4.2 and 7.4.6, respectively. But _not_ on a local environment running 7.4.30. I've attempted to reapply the entire project config on the staging environment to see if that would fix the issue without success. Seeing if I can provide some more information, but that's all I've got for now.

**Comment by kjmartens** [comment]
Sorry for the issue and delay @jrrdnx.

I am trying to duplicate this in my testing, and I can't seem to see any issues. Is this issue still happening? Just to confirm, is this hCaptcha Checkbox or Invisible? And are you able to provide the value in the `layoutJson` column for this form in the `freeform_forms` database table? 🙂

**Comment by jrrdnx** [comment]
Still occurring. And that's the thing, we're not and have never used hCaptcha on this site, only reCAPTCHA v2 Checkbox.

I'm wondering if there's an environment or some other configuration issue, because even when I pull down the production database and use that locally I can open that form builder without any issues. Just not sure how to go about debugging that. I tried removing the `Dby6EMJWj` object from the JSON below (so as to remove the captcha field from the form) as well as the reference to it from the `layout` array, but I still get the console warning and form builder is completely empty.

layoutJson:

```
{
    "composer": {
        "layout": [
            [
                {
                    "id": "oygv8Mamm",
                    "columns": [
                        "Bb10jE4K3",
                        "d1EeG8Z68",
                        "AV34dy07p"
                    ]
                },
                {
                    "id": "55PYGqgqo",
                    "columns": [
                        "rNMj1XAE6",
                        "7dGA3rzWg"
                    ]
                },
                {
                    "id": "nJv5N8ApD",
                    "columns": [
                        "QBOZ7q06y"
                    ]
                },
                {
                    "id": "VODq9zjjp",
                    "columns": [
                        "Dby6EMJWj"
                    ]
                },
                {
                    "id": "AEl6ymJLG",
                    "columns": [
                        "g8Koqd75d"
                    ]
                }
            ]
        ],
        "properties": {
            "page0": {
                "type": "page",
                "label": "Page 1"
            },
            "form": {
                "type": "form",
                "name": "Contact",
                "handle": "contact",
                "color": "#5c8f43",
                "submissionTitleFormat": "{{ dateCreated|date(\"Y-m-d H:i:s\") }}",
                "description": "",
                "formTemplate": "flexbox.html",
                "returnUrl": "",
                "storeData": true,
                "defaultStatus": 2,
                "ajaxEnabled": false
            },
            "integration": {
                "type": "integration",
                "integrationId": 0,
                "mapping": []
            },
            "connections": {
                "type": "connections",
                "list": null
            },
            "rules": {
                "type": "rules",
                "list": []
            },
            "admin_notifications": {
                "type": "admin_notifications",
                "notificationId": 1,
                "recipients": "test@example.com"
            },
            "payment": {
                "type": "payment",
                "integrationId": 0,
                "mapping": []
            },
            "Bb10jE4K3": {
                "hash": "Bb10jE4K3",
                "id": 15,
                "type": "text",
                "handle": "fullName",
                "label": "Full Name",
                "required": true,
                "instructions": "",
                "value": "",
                "placeholder": ""
            },
            "d1EeG8Z68": {
                "hash": "d1EeG8Z68",
                "id": 3,
                "type": "email",
                "handle": "email",
                "label": "Email",
                "required": false,
                "instructions": "",
                "notificationId": 0,
                "values": [],
                "placeholder": ""
            },
            "AV34dy07p": {
                "hash": "AV34dy07p",
                "id": 16,
                "type": "text",
                "handle": "phoneNumber",
                "label": "Phone Number",
                "required": false,
                "instructions": "",
                "value": "",
                "placeholder": ""
            },
            "QBOZ7q06y": {
                "hash": "QBOZ7q06y",
                "id": 12,
                "type": "textarea",
                "handle": "message",
                "label": "Message",
                "required": true,
                "instructions": "",
                "value": "",
                "placeholder": "",
                "rows": 5
            },
            "Dby6EMJWj": {
                "type": "recaptcha",
                "label": "reCAPTCHA"
            },
            "g8Koqd75d": {
                "type": "submit",
                "label": "Submit",
                "labelNext": "Submit",
                "labelPrev": "Previous",
                "disablePrev": false,
                "position": "left"
            },
            "validation": {
                "type": "validation",
                "validationType": "submit",
                "successMessage": "",
                "errorMessage": "",
                "showSpinner": false
            },
            "rNMj1XAE6": {
                "hash": "rNMj1XAE6",
                "id": 26,
                "type": "select",
                "handle": "subject",
                "label": "Subject",
                "required": true,
                "instructions": "",
                "showCustomValues": true,
                "value": "",
                "options": [
                    {
                        "label": "Test1",
                        "value": "test@example.com"
                    },
                    {
                        "label": "Test2",
                        "value": "test@example.com"
                    },
                    {
                        "label": "Test3",
                        "value": "test@example.com"
                    }
                ],
                "source": "custom",
                "target": null,
                "configuration": null,
                "values": []
            },
            "7dGA3rzWg": {
                "hash": "7dGA3rzWg",
                "id": 27,
                "type": "select",
                "handle": "school",
                "label": "School",
                "required": true,
                "instructions": "",
                "showCustomValues": false,
                "value": "",
                "options": [
                    {
                        "label": "Test1",
                        "value": "Test1"
                    },
                    {
                        "label": "Test2",
                        "value": "Test2"
                    },
                    {
                        "label": "Test3",
                        "value": "Test3"
                    },
                    {
                        "label": "Test4",
                        "value": "Test4"
                    }
                ],
                "source": "custom",
                "target": null,
                "configuration": null,
                "values": []
            }
        }
    },
    "context": {
        "page": 0,
        "hash": "7dGA3rzWg"
    }
}
```

**Comment by jrrdnx** [comment]
Can you provide any direction on where I might look to resolve this? I can provide a login to a non-production site if you need to see when/where this is occurring.

**Comment by kjmartens** [comment]
Sorry for the delay @jrrdnx.

I'm curious if clearing the template caches will resolve this issue for you. Would you be able to give that a try?

Specifically: `Utilities -> Caches -> Compiled Templates` 🙂

**Comment by jrrdnx** [comment]
Also updated Freeform to 3.13.20 and tried clearing those caches again, still getting the isHCaptcha error.

**Comment by kjmartens** [comment]
Ok, thank you for trying that. Are you able to provide access to the site then? You can send that via email to support@solspace.com. 🙂

**Comment by jrrdnx** [comment]
Account created and activation email sent. Thanks!

**Comment by kjmartens** [comment]
@jrrdnx Sorry, I am not seeing anything. Would you be able to try again? 🙂

**Comment by kjmartens** [comment]
Out of curiosity, how do you put files on the server? Do you run `composer install` on the production environment, or do you transfer files manually? 🙂

**Comment by jrrdnx** [comment]
We have build processes that run in Docker containers to handle all of the
`composer install` and front-end workflows, then everything is pushed up to
the servers via rsync before connecting via ssh and running db/backup,
migrate/all, and project-config/apply.
------------------------------------
Jarrod D Nix, Senior Front-End Developer
***@***.*** | jarrodnix.dev

**Comment by kjmartens** [comment]
Hi @jrrdnx,

Can you have a look at this similar issue here:
https://github.com/solspace/craft-freeform/issues/468#issuecomment-1275686764

> Yes that's a risky thing to do. Might I recommend `composer install`ing directly on the server instead? `composer install` is meant exactly for that scenario, it installs all of the packages at the versions in the `composer.lock` file, whereas `composer update` updates all dependencies to the latest versions generating a new lock file.
>
> `rsync` could potentially skip overwriting files based on timestamps which might cause issues, as well as not removing files as you mentioned.

It might be that your existing flow could run you into an issue like this occasionally... if absolutely necessary, you can probably continue to use your current flow, but if an issue arises like this, `composer install`ing directly on the server instead should resolve the issue. 🙂

**Comment by jrrdnx** [comment]
This was exactly it. Our newer deployment processes remove the vendor folder before running `rsync`, but this was a slightly older project that didn't have that updated workflow. Thanks for the assist!
