### ISSUE TITLE
Unauthorized User is not permitted to perform this action

### ISSUE THREAD

**Issue by EthanD775** [solspace/craft-freeform#442]
Created a new form however receiving "Unauthorized
User is not permitted to perform this action" when trying to export.. even though I have full permissions. 

1.Click export > Excel > error
2.Other forms work 

Have existing forms that export just fine

Craft CMS 3.7.43

**Additional context**
![image](https://user-images.githubusercontent.com/112096402/186683745-e32e778e-9720-4b80-b55c-11bd9dcb6343.png)
![image](https://user-images.githubusercontent.com/112096402/186683807-d30c515b-f80b-4008-9758-8d4a264e23f9.png)

**Comment by kjmartens** [comment]
Hi @EthanD775,

Can you confirm which version of Freeform you are using? And what the user/user group permissions currently are (maybe a screenshot of Freeform permissions)? 🙂

**Comment by EthanD775** [comment]
Thanks for your reply! 
To be honest I'm struggling to find where exactly the version info would be - which makes me question whether this account does fully have access to all plugin features. I've attached a screenshot of the current permissions, hopefully that helps. 
![image](https://user-images.githubusercontent.com/112096402/186791594-9d648663-8ade-47ca-a821-fd3b061bbbf6.png)

**Comment by kjmartens** [comment]
Sorry for the delay @EthanD775.

You can find the version of Freeform by visiting the Diagnostics tab inside Freeform (under settings), or inside the Craft -> Settings -> Plugins list page.

I tested this again on my side and it appears to be working without issue in the latest version of Freeform 3.x

If you are using the latest version, are you also able to confirm a few other things?

1. Just to confirm, this issue only affects the 1 form? All others are fine?
2. Does the issue affect all types of exports (not just Excel)?
3. If you attempt to export via the Submissions index page using the "Quick Export" option, does it fail there too?
4. Is there anything particular about this form that is different from the other ones? E.g has a special field type that others don't have, contains more than 1 page, has LOTS of fields, etc.

Thanks! 🙂

**Comment by kjmartens** [comment]
Hi @EthanD775, we've made a fix in Freeform 3.13.19 and 4.0.3 that might resolve this issue. Can you update and retest? 🙂
