### ISSUE TITLE
Tailwind 3 template is ignoring custom classes on select fields

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#443]
**Describe the bug or issue you're experiencing**
I have a custom class assigned to a select field on my form, "hidden-test" for example. This is correctly applied to the field's label and instructions, but not the select field itself.

Field layout:
![image](https://user-images.githubusercontent.com/1250017/186886114-7c879db7-7055-41c5-992f-2fc746ee984a.png)

Source code:
![image](https://user-images.githubusercontent.com/1250017/186886065-bdcef3b9-005e-4701-a310-2f5cb7c5a315.png)

**Steps to reproduce**

1. Add a custom class to a selext field's "input" attribute

**Expected behavior**
The custom class should be applied to select fields, not just text fields

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.2.2
- Freeform Version: 4.0.2
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Thanks @darylknight. We'll check into it shortly. 🙂

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 3.13.19 and 4.0.3. 🙂
