### ISSUE TITLE
Conditional 

### ISSUE THREAD

**Issue by Damoz101** [solspace/craft-freeform#444]
Conditional Rules not applying
Not hiding before conditions are met.

**Steps to reproduce**

1.Add four feilds
"Select" "Test1" option with 3 choices "A" "B" "C"
"Text" "TestA" 
"Text" "TestB" 
"Text" "TestC"

2. Conditional Rules Applied 
Show "TestA" this item when any of its criteria match
"Test1" is A
Show "TestB" this item when any of its criteria match
"Test1" is B
Show "TestC" this item when any of its criteria match
"Test1" is C

**Expected behavior**
I would expect this to hide "TestA" "TestB" "TestC" until one of these is selected in "Test1"
However they are all being shown by default.

**Craft & Plugin Info (please com

plete the following information):**
- Craft Version: 3.7.48 Pro
- Freeform Version: 3.13.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**
Im very new to Craft/Freeform so could be an oversite.

![FreeForm](https://user-images.githubusercontent.com/11671508/187104685-76e744ae-6554-4a75-ad0c-b97690546e05.png)

![FreeForm1](https://user-images.githubusercontent.com/11671508/187104745-34afc12a-a837-4cff-9f32-13da14457256.png)

**Comment by kjmartens** [comment]
Hi @Damoz101,

When you load the form in the front end, are you seeing any JS errors in the browser console? I'm wondering if it's a JS error, perhaps due either to your templating or how you're loading Freeform's JS files.

The [Freeform Javascript Insertion Location](https://docs.solspace.com/craft/freeform/v4/setup/settings.html#form-behavior) setting should be set to **Inside Form** or **Page Footer**. If you chose **None**, you need to make sure you load it manually. If you chose **Page Footer**, you need to make sure that your template contains a closing `</body` tag so Freeform knows where to insert the scripts. 🙂 

What do you have set for the [Freeform Script Insert Type](https://docs.solspace.com/craft/freeform/v4/setup/settings.html#form-behavior) setting? If it's "Static URLs", try changing it to "As Files" and see if that helps.
