### ISSUE TITLE
Garbage collection doesn't remove deleted submissions

### ISSUE THREAD

**Issue by SarahOorts** [solspace/craft-freeform#447]
One of our websites got hit by a bunch of bots that created thousands of submissions (which were not labelled as spam because of a setup issue on our side). We removed them all through a console command and ran Craft's garbage collection but they remain in trash.

**Steps to reproduce**

1. Delete submission
2. Run `php craft gc/run`
3. Check Trashed submissions

**Expected behavior**
Deleted submissions should be hard deleted when garbage collection runs.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.2.0.2
- Freeform Version: 4.0.0-beta.18
- Freeform Edition: Lite
- Fresh Install or Upgrade: Upgrade from 2 > 3 > 4

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the long delay @SarahOorts. I can duplicate this as well. We'll get it fixed shortly. 🙂
