### ISSUE TITLE
Don't allow editors to create file-based email notification templates

### ISSUE THREAD

**Issue by thisisjamessmith** [solspace/craft-freeform#448]
As devs, it's useful for us to use file-based email notification templates so that we can put them in version control and have all the usual benefits of Twig and IDEs etc, so we don't want to disable file-based notifications entirely.

But editors should not be allowed to create file-based email notifications because it will break our deployment process which is based on Git hooks.

- Craft Version: 4.2.1
- Freeform Version: 4.0.2
- Freeform Edition: Lite

**Comment by kjmartens** [comment]
Thanks for your feedback on this, @thisisjamessmith. We'll check into adding an additional setting or permission that can control this behavior. 🙂

**Comment by kjmartens** [comment]
We've now added a setting in Freeform 4.0.4 which allows you to disable the creation and editing of email notification templates inside the control panel. 🙂
