### ISSUE TITLE
Multi Page Forms with File Upload Drag & Drop not enforcing required file after file has been deleted.

### ISSUE THREAD

**Issue by mambose** [solspace/craft-freeform#455]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Create a multi page form with required file upload drag and drop fields
2. Fill out form, upload required file and proceed to next page
3. Go back to previous page
4. Delete required file
5. Go to next page
6. File is no longer required.

**Expected behavior**

Should not allow you to proceed to next step as file field is required.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.2.4
- Freeform Version: 4.0.3
- Freeform Edition: Pro
- Fresh Install or Upgrade:

**Additional context**

- Multi Page form with File Upload Drag & Drop - tried with Ajax enabled and disabled.

**Comment by kjmartens** [comment]
Sorry for the delay, and thanks for reporting this @mambose.

I can duplicate this issue in my testing as well. We'll make a fix for it shortly. 🙂

**Comment by kjmartens** [comment]
This has now been resolved in Freeform 3.13.20 and 4.0.4. 🙂
