### ISSUE TITLE
Multi page forms checkbox group issue

### ISSUE THREAD

**Issue by helenatnixon** [solspace/craft-freeform#458]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Create a multi page form with more than one page
2. Put a checkbox group on the first page
3. Test the form by selecting one or more boxes on the first page, then go to next page
4. Go to previous page, uncheck boxes, go to next page
5. Go to previous page, previously unchecked boxes have rechecked themselves

**Expected behavior**

Checked then unchecked boxes should remain unchecked

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.48
- Freeform Version: 3.13.14
- Freeform Edition: Lite
- Fresh Install or Upgrade: has been upgraded in recent past, but not tried multi-page forms with previous versions

**Additional context**

**Comment by kjmartens** [comment]
Thanks for reporting this issue @helenatnixon.

I can duplicate this issue in my testing as well. To confirm it only seems to happen if I have some checked initially, and I then uncheck ALL of them. If I uncheck some and check off at least one other, it seems to work.

We'll work on a fix for this shortly. 🙂

**Comment by kjmartens** [comment]
This has now been resolved in Freeform 3.13.20 and 4.0.4. 🙂
