### ISSUE TITLE
Widgets available for users without permission

### ISSUE THREAD

**Issue by FrDH** [solspace/craft-freeform#459]
**Describe the bug or issue you're experiencing**
Users that can't do any freeform stuff due to not having those permissions, can add the freeform widgets in the dashboard.
According to the craftcms team, each plugin is supposed to manage the permissions of their own widgets.

**Steps to reproduce**

1. Create a user without any permissions and log in as that user
2. Go to the dashboard and find yourself able to add all freeform widgets.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Thanks for reporting this, @FrDH. We'll have a look at this and see what we can do. 🙂

**Comment by FrDH** [comment]
Freeform 3

**Comment by kjmartens** [comment]
This has now been resolved in Freeform 3.13.20 and 4.0.4. 🙂
