### ISSUE TITLE
Uncaught ReferenceError: formTypes is not defined

### ISSUE THREAD

**Issue by FrDH** [solspace/craft-freeform#468]
**Describe the bug or issue you're experiencing**
The CP for freeform appears to be broken after updating to 3.13.20:
When trying to edit a form in the CP, the page remains empty, devtools logs the following error:
```
builder.js?v=1664783623:2 Uncaught ReferenceError: formTypes is not defined
    at 76938 (builder.js?v=1664783623:2:730602)
    at r (builder.js?v=1664783623:2:760921)
    at builder.js?v=1664783623:2:762490
    at r.O (builder.js?v=1664783623:2:761307)
    at builder.js?v=1664783623:2:762506
    at builder.js?v=1664783623:2:762511
````

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.55.2
- Freeform Version: 3.13.20
- Freeform Edition: PRO
- Fresh Install or Upgrade: fresh intall

**Additional context**
Same happens when trying to create a new form.

**Comment by FrDH** [comment]
Thank you for looking into this.
I had a look and all forms (only 4) are of the type Regular. See screenshot.

<img width="278" alt="Schermafbeelding 2022-10-04 om 14 50 57" src="https://user-images.githubusercontent.com/1387163/193824020-7e21e262-660b-4db9-adb2-205be0fcf322.png">

**Comment by FrDH** [comment]
<img width="258" alt="Schermafbeelding 2022-10-04 om 14 52 38" src="https://user-images.githubusercontent.com/1387163/193824180-e5b5f402-7ee1-4a9a-aef9-f59bfd2721a2.png">

**Comment by JamesNock** [comment]
A quick fix is to hop on to your database and run:

```
UPDATE freeform_forms SET type = 'Solspace\Freeform\Form\Types\Regular' WHERE type = '';
```

**Comment by FrDH** [comment]
Thank you @JamesNock but all 4 form have a type (see the screenshot) so that query wouldn't do anything. (right?)

**Comment by FrDH** [comment]
My browser crashed trying to copy/paste all that :)

**Comment by FrDH** [comment]
Somehow, the editing the forms is only broken on staging and production environments, not on my local development environment (which is up to date with the production branche, I even pulled in the DB from production).

Some differences I could find in local and production:
PHP: local 7.4.21 / prod 7.4.30
SQL: local 5.7.34 / prod 5.5.5

**Comment by FrDH** [comment]
0 results
![Schermafbeelding 2022-10-07 om 08 30 09](https://user-images.githubusercontent.com/1387163/194482389-f628b2e6-b520-41d4-8adb-d55aa468f581.png)

Here's the list of vars in the source:
![Schermafbeelding 2022-10-07 om 08 30 20](https://user-images.githubusercontent.com/1387163/194482442-1b604acd-a825-414a-b382-0a2015ed759e.png)

**Comment by FrDH** [comment]
Good news :)
After removing the `vendor/solspace` directory and rerunning the deployment the forms are rendered again!

Maybe some old file that was renamed (from camelcase to lowercase or something) was still present and messing things up.

Thank you all for digging into this. 👍

**Comment by FrDH** [comment]
Just to let you know, the issue occurred on all sites where we updated freeform to 3.13.19 :(

**Comment by FrDH** [comment]
Yes, that still works

**Comment by FrDH** [comment]
not that much magic going on in the pipeline, basically we do a `composer install` (with some params) and then rsync all directories that should be deployed (including the `vendor` directory).
Afterwards we call the `migrate/all` and `clear-caches/all` commands.

Our best guess is that rsync doesn't remove the old directories before copying the new ones (to prevent downtime). This way, files that should have been removed, remain on the server.

Hope this helps.

**Comment by FrDH** [comment]
Thanks, I'll mention this in our next dev meeting.
