### ISSUE TITLE
Not all email notifications are selectable inside a form

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft-freeform#470]
**Describe the bug or issue you're experiencing**
When you have a combination of File - and Database templates, and you create new database templates some file templates aren't visible anymore to select inside the form editor

**Steps to reproduce**

1. Have some email file templates
2. Start to add some more email database templates
3. Every time I add 1 more extra database template another file template isn't showing up anymore in the dropdown

**Expected behavior**
All the file and database templates should be shown and selectable. 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.2.5.2
- Freeform Version: 4.0.4
- Freeform Edition: PRO
- Fresh Install or Upgrade: Fresh install

**Comment by kjmartens** [comment]
Sorry for the trouble, @WHITE-developer. I can duplicate this as well. We'll get it fixed shortly. 🙂

**Comment by kjmartens** [comment]
This should be resolved in Freeform 4.0.5 now. 🙂
