### ISSUE TITLE
Form doesn't submit with ReCaptcha v3

### ISSUE THREAD

**Issue by HannahDeWachter** [solspace/craft-freeform#472]
**Describe the bug or issue you're experiencing**
We have a contact form (Freeform) that gets a lot of spam. We enabled ReCaptcha v3 in Freeform to fix this problem. However, with recaptcha added the form does not submit, it keeps loading.

**Steps to reproduce**

1. Make a form
2. Enabled ReCaptcha with v3 credentials
3. Submit the form

**Expected behavior**
Form gets submitted.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.2.5.2
- Freeform Version: 4.0.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Code to render form:
`{{ craft.freeform.form('contactForm', { labelClass: 'form__label', submitClass: "btn spacer spacer--med" }).render() }}`

**Comment by kjmartens** [comment]
Hi @HannahDeWachter,

Can you tell me more about your setup?

1. Are you using a custom formatting template or one that is included with Freeform? If custom, can you share what it looks like?
2. What else is inside the template where `craft.freeform.form` is being included? Perhaps you can share what that template looks like as well and/or include a link to the site page if possible.
3. Are you caching this page at all?

Thanks 🙂

**Comment by HannahDeWachter** [comment]
Hi @kjmartens 

We changed the ReCaptcha from v3 back to v2 Checkbox and this sees to work now.
Thank you.
