### ISSUE TITLE
extractColumnName() function only returns the first table name it encounters with a matching column

### ISSUE THREAD

**Issue by marktundra** [solspace/craft-freeform#473]
When using `craft.freeform.submissions({ fieldSearch: { email: "*test@email.com*" } }).one()`, the result returns empty because I have 2 forms with the field "email". `private function extractColumnName(...)` incorrectly returns a single string of the form submission table + column name to add to the where clause, however it should include all instances of forms where that column is present by returning an array which is handled correctly using orWhere().

**Comment by kjmartens** [comment]
Sorry for the trouble, @marktundra. This should now be resolved in Freeform 4.0.6. 🙂
