### ISSUE TITLE
Deleting form submissions crashes and runs out of memory

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#485]
**Describe the bug or issue you're experiencing**
We're using Freeform as an age gate for an alcohol website. I need to "save submissions to the database" (form setting), because I'm using the most recent submission on the template to check the submitted date is more than 21 years ago. 

Two separate issues / requests:

1. I don't actually want those submissions in the database, but I can't check the submitted date if this isn't enabled. It would be great if we could set Freeform to automatically purge submissions to that form after X days, just like the spam system works.
2. We have 33,000 submissions to that form. If I go to Submissions and select Delete All, it give sme a server error because it immediately runs out of memory. Perhaps this could be avoided if Freeform tried to batch that operation into smaller chunks instead of requesting to do all 33k in one go?
 
![image](https://user-images.githubusercontent.com/1250017/198012006-878930aa-e01b-45f7-afe9-328370bedb80.png)

```
[26-Oct-2022 04:10:18 America/Los_Angeles] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in /home/ploi/sitename.com/vendor/yiisoft
```

**Steps to reproduce**

1. Have lots of form submissions
2. Try to delete them all in one go on a small server

**Expected behavior**
Freeform should batch this operation so it doesn't run out of memory

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.0
- Freeform Version: 4.0.7
- Freeform Edition: Pro

**Comment by darylknight** [comment]
If you're suggesting writing a PHP module, no that wouldn't be possible for us. We're currently doing it like this:

```
{# * Make sure AJAX is disabled on the age gate form #}
{# * Make sure the form is set to "save submissions" - otherwise the below code breaks (it relies on checking the previous submission) #}

{% set form = craft.freeform.form('ageGate') %}

{% if getCookie('ageGateCookie') %}
  {# ? There is a cookie set, which means they've passed the age gate within the last 30 days #}
{% else %}
  {# No cookie set, so check the age #}
  {% if form %}
    {# Check if the form exists before doing any of this #}
    {% if form.submittedSuccessfully %}
      {# form was submitted successfully #}
      {% set submission =
        craft.freeform.submissions({
          form: 'ageGate'
        }).one()
      %}
      {% if submission %}
        {% if (submission.dateOfBirth|date('U')) > ('-21 years'|date('U')) %}
          {# Not old enough. Show the modal again with an error #}
          {# ? No age gate cookie found, and no form submitted - so show the age gate form #}
          {% include '_includes/ageGateModal' with {
            mode: 'showError'
          } %}
        {% else %}
          {# They're more than 21, so set cookie #}
          {% do setCookie('ageGateCookie', 'ageGatePassed', now|date_modify('+30 days').timestamp) %}
          {# Age gate passed, so show the website #}
        {% endif %}
      {% endif %}
    {% else %}
      {# ? No age gate cookie found, and no form submitted - so show the age gate form #}
      {% include '_includes/ageGateModal' with {
        mode: 'showForm'
      } %}
    {% endif %}
  {% else %}
    {# There is no form called ageGate, so we can't check age #}
  {% endif %}
{% endif %}
```

**Comment by darylknight** [comment]
Thanks for your feedback Gustavs. We have zero raw PHP experience, so I don't think adding a module is going to work for us long term. Getting the batch deletions fixed should help though, thank you

**Comment by darylknight** [comment]
Thanks Gustav :) I might, when I have the brainspace available. Apprecite it.

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 4.0.8. 🙂

**Comment by darylknight** [comment]
Excellent, thank you. Is there any way to track if this is working? I just tried to delete 45,000 entries, and the list just went slightly lighter and did nothing for 20 minutes. There was a short spike in CPU usage, but nothing to suggest it's still going, and all 45k submissions are still there.

![image](https://user-images.githubusercontent.com/1250017/203267491-f7ffef27-5c7c-4272-ab37-da7de46165b4.png)

**Comment by darylknight** [comment]
Update - I get a "server error occured" message in the bottom left after a few minutes, there are no log files generated to find out what the error was. I'm guesssing perhaps it runs out of memory or something.

**Comment by kjmartens** [comment]
Sorry @darylknight. I'll have a developer check into it again.

**Comment by darylknight** [comment]
Pinging for an update on this. On a separate site, they got DDOS'd at the end of last year and now have 700,000 spam submissions in their database. If I try to delete all of these, the site showed a spinning wheel for about a minute, then showed "a server error occured". Freeform is set to retain spam messages for 3 days, but there are spam submissions dating back to September.

I had a quick look at the database to see if I could remove them directly, but it looks like the spam submissions are stored alongside the genuine ones. How can I clear out the spam submissions?

**Comment by gustavs-gutmanis** [comment]
Hi @darylknight 
We have added batch processing to the spam purge functionality, but since your case is so severe, I guess the script time-out is kicking in and crashing the process.

You can, however delete all spam submissions and the respective elements with this query:
```
DELETE e
FROM elements e
INNER JOIN freeform_submissions fs ON e.id = fs.id AND fs.isSpam = true;
```

### Be sure to make a backup of your database beforehand though!

**Comment by darylknight** [comment]
Thanks for replying so quickly @gustavs-gutmanis. I just ran this on a local copy of the database and it completed successfully after 18 minutes
