### ISSUE TITLE
Bug: Freeform v4.0.7 Submitting a form fails to submit a notification

### ISSUE THREAD

**Issue by CAIDcreative** [solspace/craft-freeform#498]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

Submitting a form which sent a notification would trigger an sql error. I found out it was because it was passing the notification handle but trying to query for a id (which caused a postgresql error).

In the vendor file "vendor/solspace/craft-freeform/packages/plugin/src/Services/Notifications/NotificationDatabaseService.php" I changed line 27 from:

`return NotificationRecord::find()->where(['id' => $id])->one();`

to

`return is_numeric($id) ? NotificationRecord::find()->where(['id' => $id])->one() : NotificationRecord::find()->where(['handle' => $id])->one();`

This fixed the issue for the moment, but yeah editing the vendor file isn't a permanent solution. Any fixes would be appreciated.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.3.1
- Freeform Version: 4.0.7
- Freeform Edition: Pro 
- Fresh Install or Upgrade: Upgrade
- Also using Postgres 13

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 4.0.8. 🙂
