### ISSUE TITLE
Dynamic Recipients field - email custom field is not available when using 'Entries' as the source.

### ISSUE THREAD

**Issue by thisisjamessmith** [solspace/craft-freeform#501]
**Describe the bug or issue you're experiencing**

Hiya, I'm trying to set up the Dynamic Recipients field. I'd like to be able to pull the options from an existing section. Each entry in the relevant section has an email field assigned in its field layout. However, after filtering the Source down to the right entries, the "Option Value" dropdown does not contain the email field for some reason.

**Steps to reproduce**

1. Have a Dynamic Recipients field, a section with a custom field of type 'email' (Craft's native email fieldtype)
2. Put the Dynamic Recipients field in a form and set its Source as Entries and Target as the relevant section with the email field
3. See that the email field doesn't show up in the list of Option Values. (If anything, I'd expect this list to filter out everything _except_ email fields)

**Expected behavior**

Ability to map each option to a pre-defined email address

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.1
- Freeform Version: 4.0.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: freshish

**Comment by kjmartens** [comment]
Sorry for the trouble @thisisjamessmith.

I just tested this again on my site, and it seems to work fine for me. To be clear, you're saying that your Email field type is completely missing from the list of available fields? Are you able to share with me the setup for this Email field? Perhaps it's related to how it is set up that Freeform seems to be missing it. 🙂

**Comment by thisisjamessmith** [comment]
Strange that it's working for you... The email field is standard, nothing special about it. I haven't renamed its label in the field layout, and it's just completely absent from the list of available fields. 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/2416106/201877417-bbc45b8f-5139-461b-b85f-83535f9e7670.png">

**Comment by kjmartens** [comment]
Ok, I played around with it on my end, and I was able to determine that Freeform is blocking the field if it's named with a handle of `email`. In my initial testing, my email field handle was something different. I wonder if it's getting mixed up with Craft's own **Email** field for user accounts, which Freeform also supports.

I've made a note about this and we'll get it fixed. In the meantime, if you're able to adjust the value fo the handle of that Email field, I believe that would be a workaround for now. 🙂

**Comment by kjmartens** [comment]
After checking with a developer, this is a current limitation in Freeform, unfortunately. We are working on some larger changes to Freeform though, so it's something that we'll be able to address in the future. In the meantime, `email` is a reserved handle for this feature in Freeform.
