### ISSUE TITLE
Save & Continue Later button doesn't work

### ISSUE THREAD

**Issue by croxton** [solspace/craft-freeform#502]
**Describe the bug or issue you're experiencing**

I added 'Save & continue later' buttons to each page of a multi-page form, as described here:
https://docs.solspace.com/craft/freeform/v4/overview/save-continue-later.html#overview

Clicking the button submits the form for validation just like the 'Submit' button - it doesn't save the form data and redirect to the `Return URL` set for the `Save & continue later` field. Setting the `Return URL` directly on the field or in the template makes no difference. I tried the various default formatting templates but it's the same behaviour with all of them.

**Steps to reproduce**

1. Add a `Save & Continue later` button to a multi-page form as described here: https://docs.solspace.com/craft/freeform/v4/overview/save-continue-later.html#overview
2. Add next/previous buttons to each page too, 
    - on page 1 we have `Save & Continue later` and `Next`
    - on page 2+ we have `Save & Continue later`, `Previous` and `Next`
3. Enter some incomplete data into the form (on any page) and click the `Save & Continue later` button.

**Expected behavior**

1. Partial form data should be saved to database
2. User should be redirected to 'saved form' template (specified by `savedFormRedirect`)
3. Email notification sent to the email address selected for the `Save & Continue later` button

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.1
- Freeform Version: 4.0.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

Loading Freeform script manually. Template code below:

```twig
{{ form.render( {
   id: 'js-instruction-form',
     overrideValues: {
         development: entry.title ~ (entry.description ? ' – ' ~ entry.description : '')
      },
      returnUrl: "{{ siteUrl }}developments/instruction/{{ submission.id }}/{{ submission.token }}",
      savedFormRedirect: "{{ siteUrl }}developments/save-progress?&session-token={token}&key={key}",
      savedSession: {
         token: submissionToken,
         key: submissionKey,
      }
}) }}
{{ craft.freeform.loadFreeformPlugin() }}
```

**Comment by croxton** [comment]
Clicking the save button performs a submit, exactly as if I'd clicked the submit/next button. If there are form errors they are shown on the current page, if not the form progresses to the next page.

There are 4 email fields on the page 1 form:
* The first email field is required and linked to the `save and continue later` button. I tried completing this field and leaving it blank, but same result. The field has the handle `email`. It is also used for the recipient of the form's email notification.
* The other 3 email fields are conditionally shown depending on the value of a select menu. These are set to required (that is only enforced if they are visible). These have handles `emailP2`, `emailP3` and `emailP4`. I tried filling in some or all of these, but got the same result.

I tried saving from page 2 and 3 (which have no email fields) but same result.

Buttons are rendered like this in the form formatting template:

```{{ field.render({ class: "c-button bg-accent hover:bg-accent-dark text-white" }) }}```

The save button is rendered with the `data-freeform-action="save"`attribute as expected.

I tried the various default formatting templates but had the same problem.

I didn't see any JS errors.

Not sure if this is relevant, but I note that there are two hidden fields in the form, generated by Freeform by default.

```
<input type="hidden" name="freeform-action" value="submit">
...
<input type="hidden" name="action" value="freeform/submit">
```

 I experimented with changing these (in devtools) to "save" and "freeform/save" but it just stopped the form submit working entirely.

**Comment by kjmartens** [comment]
Hi @croxton, sorry for the long delay...

I am revisiting this one now and I am wondering if there's a misunderstanding. When you say it behaves as if you'd clicked the submit/next button, are you seeing Freeform's validation or browser validation (or perhaps even another third party validation such as [Parsley](https://docs.solspace.com/craft/freeform/v4/guides/form-validation-with-parsley.html)? It's important to note that with the **Save & Continue Later** feature, only Freeform's built-in validation is bypassed.

If you have browser validation, it will not be aware, so it would be necessary to disable that with `useRequiredAttribute: false` (or remove the parameter). If using something like Parsley, I'm unsure if there would be a way to work around it.

If what you're seeing is Freeform's built-in validation still, then let me know. 🙂
