### ISSUE TITLE
Submission marked as spam after session ended

### ISSUE THREAD

**Issue by FrDH** [solspace/craft-freeform#505]
**Describe the bug or issue you're experiencing**
Apparently, a lot of our clients have users that let their session end before submitting a form. This results in the page being reloaded with an error message and all fields are pre-filled, if the user now submits the form for a second time, it all appears to work as hoped, but unfortunately the submission is marked as spam (and no admin notification is sent).
As a patch, we already upped the session time:
```
ini_set('session.gc_maxlifetime', 14400);
```

**Steps to reproduce**

1. Create a form and add it to a page.
2. Kill the session by adding `session_destroy();` at the bottom of `public_html/index.php`.
3. Visit the page
4. Remove or comment out the `session_destroy();` so the next session wont be killed.
5. Submit the form, you get an error saying something went wrong
6. Submit the form once again.
7. Check freeform spam folder

**Expected behavior**
I'd expect the form not to end up in the spam folder.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7
- Freeform Version: 3.13
- Freeform Edition: PRO
- Fresh Install or Upgrade: fresh install

**Additional context**

**Comment by kjmartens** [comment]
Hi @FrDH,

What is the reason shown in the Spam Folder? Do you also have the JS Enhancement enabled for the Honeypot? 🙂

**Comment by FrDH** [comment]
> Marked as spam because:
> Honeypot check failed

Both "Freeform honeypot" and "Javascript enhancement" are enabled.

**Comment by FrDH** [comment]
Any news on this?

**Comment by FrDH** [comment]
We're already using the `As an encrypted payload (recommended)` option.

**Comment by kjmartens** [comment]
Ok, so it seems like the issue is specifically with the JS Honeypot enhancement. That particular feature still relies on the PHP session. We recommend either increasing the PHP session limit or disabling the JS enhancement for now.

I've made a note about this for future consideration to see if we can have it work with Encrypted Payloads and not expire with the PHP session.

Sorry for the inconvenience. 🙁

**Comment by FrDH** [comment]
Thank you for taking the time to investigate, I'll report this back to the team and see if we can make it work for us.
