### ISSUE TITLE
Failed Stripe payment

### ISSUE THREAD

**Issue by LoriWJ** [solspace/craft-freeform#526]
**Describe the bug or issue you're experiencing**

We have a donation form that uses the Stripe integration. Most payments go through fine but one failed on 18 November. The error message says:

> "Unrecognized request URL (GET: /v1/payment_intents/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/" 

The client wants to know what could have caused the error but I can't find anything in the Stripe documentation.

**Steps to reproduce**

I can't reproduce the error and I don't know what the website user did.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.22
- Freeform Version: 3.12.12
- Freeform Edition:
- Fresh Install or Upgrade:

**Comment by kjmartens** [comment]
Sorry for the trouble @LoriWJ.

Just to clarify, the issue happened once? How many successful ones happened in that timeframe? And where did that error message show up? 🙂 

There are a few updates available that specifically address issues with Payments. Probably a good idea to update to the latest 3.13.x version in the near future. 🙂

**Comment by LoriWJ** [comment]
Yes, it happened once. We had several successful payments before and after that one. The error message shows in the right sidebar of the form submission details (under where it says that the payment failed). Hope that gives you enough info. I'd really like some info that I can go back to the client with, e.g. could the error be caused by the card being declined?

**Comment by kjmartens** [comment]
Sorry for the delay...

Do you have submission throttling enabled (under Spam Settings)? If so, and if it's too aggressive, it could block the submission and cause an error like this. If not, is there any chance this one payment submission ended up in the Spam folder (and then approved)? We've heard of this kind of error popping up with some others in the past, but has usually been an issue with their template, or one of the ones I've mentioned above. 🙂

**Comment by LoriWJ** [comment]
Form submission throttling is set at 60 submissions per minute, but I don't think that anyone moved this submission from the spam folder.

**Comment by kjmartens** [comment]
Do you think it's possible you were receiving as much as 60 submissions in 1 minute (across ALL users and ALL forms) for the site?

**Comment by LoriWJ** [comment]
It's not that kind of website – they had six submissions across all forms that day and they were spaced at least half an hour apart.

**Comment by kjmartens** [comment]
The only other thing I can guess is that maybe the user's session timed out (e.g. maybe they had the payment page open and returned to it later)? It's hard to make a guess here when there's just one instance of it and no way to duplicate this issue. 😕

**Comment by LoriWJ** [comment]
Ok, thanks for the info.
