### ISSUE TITLE
Recaptcha not loading on interaction if only selects change

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft-freeform#540]
We have a form where all data is pre-filled in input fields, only a few selects (dropdowns) have to be filled in. We have "Only load Captcha scripts once the user interacts with the form?" enabled. But if you only change the selects, recaptcha isn't loaded. Only when we click in a pre-filled input, recaptcha is loaded.

Is it possible to load recaptcha also when a select changes?

**Craft & Plugin Info:**

- Craft Version: 4.2.7
- Freeform Version: 4.0.8
- Freeform Edition: Pro

**Comment by kjmartens** [comment]
Hi @WHITE-developer,

Are you able to provide me with more context for this? I am trying to duplicate the issue and it seems to work fine for me. 🙂 

1. Which reCAPTCHA version and type are you using?
2. Which browser are you using?
3. Are you using any kind of additional validation layer?

**Comment by WHITE-developer** [comment]
Hi @kjmartens 

![image](https://user-images.githubusercontent.com/22771556/207565119-d30ea89e-362f-44fc-99ff-e2f4c6443749.png)
This is the form we have. All 3 inputs are prefilled, so no interaction with those. Only the 2 selects in the bottom have to be changed.

1. V3
2. Chrome (Version 108.0.5359.98)
3. No, no other validation layer

**Comment by WHITE-developer** [comment]
@kjmartens will investigate some other thing first. Maybe it has to do with the nice-select we use over the select items.

**Comment by kjmartens** [comment]
@WHITE-developer, that sounds like it could cause some trouble for sure.
