### ISSUE TITLE
dynamicNotification only accepts ID, not handle

### ISSUE THREAD

**Issue by alexr8** [solspace/craft-freeform#541]
**Describe the bug or issue you're experiencing**

When using `dynamicNotification` parameter in the freeform.form tag, the documentation states:

`For Database entry based templates, specify the handle for template`

However this will generate an error that it can't find a notification template with the ID of 'myNotificationHandle'. If this is instead switched to the ID (by viewing the notification template in the admin and copying the id out of the URL), it works fine.

**Steps to reproduce**

1. Create a database email notification
2. Create a form with a `dynamicNotification`
3. Supply the notification handle
4. Submit
5. View error log

**Expected behavior**
The `dynamicNotification` parameter should accept the handle instead of the ID as described in the docs.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 4.2.4
- Freeform Version: Pro (trial)
- Freeform Edition: 4.0.3
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
Hi @alexr8,

I think this is an issue with your older version of Freeform (4.0.3). This was resolved in Freeform 4.0.8+. Can you try updating and try again? 🙂
