### ISSUE TITLE
ParseError syntax error, unexpected ')' - Cookies.php line 43

### ISSUE THREAD

**Issue by juddlyon** [solspace/craft-freeform#543]
The comma after the array on line 42 of `/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Form/Tracking/Cookies.php` triggers an error in PHP 7.2 (I'm running 7.2.34 and the [requirements say 7.2.5+](https://docs.solspace.com/craft/freeform/v3/setup/installing-updating.html#requirements) should work). Removing the comma fixes the issue.

PHP 7.3 and up works fine. I can't upgrade to PHP 8 for this server for another month unfortunately.

- Craft Version: Craft CMS 3.7.61
- Freeform Version: 3.13.22
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade
- PHP Version:

**Comment by kjmartens** [comment]
Sorry about this @juddlyon. We'll get it fixed shortly!

**Comment by kjmartens** [comment]
This is now resolved in Freeform 3.13.22.1. Sorry again for the trouble 🙂

**Comment by juddlyon** [comment]
Thanks @kjmartens!
